### PR TITLE
Fixes E2E, workaround ActivityLogs API failure

### PR DESCRIPTION
**Pull request by drewandersonnz**
This reverts commit f334a42a40aceb2bdbb6689607bf1c945384933d.

E2E failures have been characterised as a mismatch in API versions at Azure. 
* api-version=2015-04-01 fails to see some objects
* api-version=2017-03-01-preview (same as portal.azure.com): all objects are present

This workaround will be in place until at least most of 2nd half 2021 while Azure migrates the API underneath.

### CODE REVIEW

**Comment by drewandersonnz** [comment]
E2E failure reproduced with logs, information provided to upstream case. 

We can re-use this PR to re-trigger the fault as required, and for re-testing if upstream comes back saying they have fixed the root cause.

**Comment by drewandersonnz** [comment]
Re-testing, want to get a successful result now to provide correlation ids to upstream case.

**Comment by drewandersonnz** [comment]
Test panic'd :-( retry

**Comment by mjudeikis** [comment]
@drewandersonnz can be closed?

**Pull request closed without merging**
