### PR TITLE
Another start at the env refactor

### PR DESCRIPTION
**Pull request by jim-minter**
This PR separates out a new smaller interface, env.Core, from env.Interface.  The idea is that env.Core aggregates ubiquitous (RP_MODE, instance metadata, RP authorizer) or essential (keyvault info to enable connecting to the database) environment information shared across all RP services.

Unlike #960, this PR leaves the rest of env.Interface untouched so there's much less refactoring in core RP code, at least for now.  Everything here is likely to be a requirement for adding new RP services.

### CODE REVIEW

**Comment by jim-minter** [comment]
@asalkeld, @mjudeikis it's a tall ask but if you have a chance to look at this it'd be appreciated

**Review by mjudeikis — DISMISSED** [review]

**Comment by jim-minter** [comment]
just a rebase

**Comment by mjudeikis** [comment]
lgtm

**Pull request merged**
