### PR TITLE
Migrate apiextensions from v1beta1 to v1

### PR DESCRIPTION
**Pull request by drewandersonnz**
### Which issue this PR addresses:

Fixes https://github.com/Azure/ARO-RP/issues/1291

The module referenced updated at this PR: 
https://github.com/kubernetes-sigs/controller-tools/pull/468

### What this PR does / why we need it:

Updates module to 0.5.0, to at least receive the changes deprecating the `apiVersion: apiextensions.k8s.io/v1beta1` specification.

### Test plan for issue:

Existing integration tests should cover this case. 

### Is there any documentation that needs to be updated for this PR?

No, just a module update.

### CODE REVIEW

**Comment by drewandersonnz** [comment]
Tests completed for this change:
* `make test-go` - `PASS`
* build new cluster with v0.3.0 (existing in code), trigger upgrade to v0.5.0: success, object updated to new version
* build new cluster with v0.5.0 (new code change): success, object new version

**Comment by mjudeikis** [comment]
@drewandersonnz looks very close.
There is few more nits we need to change here. If you run bellow multiple times you can see that PutOrPatch things it needs to change object again and again. This is due to fact that Dynamic kuberentes client we use (`util/dynamichelper/dynamichelper/go`) is not aware how to handle merge of old and new objects for extension server v1. 
```
curl -k -X PATCH      -H 'Content-Type: application/json'      "https://localhost:8443/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUP}/providers/Microsoft.RedHatOpenShift/openShiftClusters/${CLUSTER}?api-version=admin" -d {}
```

Looks for merge function and you should add something like this:
```
	case *extensionsv1beta1.CustomResourceDefinition:
		old, new := old.(*extensionsv1beta1.CustomResourceDefinition), new.(*extensionsv1beta1.CustomResourceDefinition)
		new.Status = old.Status

	case *extensionsv1.CustomResourceDefinition:
		old, new := old.(*extensionsv1.CustomResourceDefinition), new.(*extensionsv1.CustomResourceDefinition)
		new.Status = old.Status
```

And I'm wondering if we need to keep `extensionsv1beta1` at all in our code base? Would this not remove need to this API at all? for new clusters im 100% sure we can drop it. Just a question if we need support for it while updating the old clusters.

**Comment by drewandersonnz** [comment]
@mjudeikis I see what you mean about the repeat change. 

The code section you mentioned seems to have stopped that point. 
I have also removed apiextensions/v1beta1 from scheme.go 

Retest?

**Comment by mjudeikis** [comment]
Im 100% sure created will work (E2E will show this too). 
Upgrades now are up for question, so just to be sure would be good.

**Comment by drewandersonnz** [comment]
E2E failed due to `OS Provisioning for VM 'v4-e2e-v123-east-xyz-master-0' did not finish in the allotted time.`

This should be unrelated. Retry.

**Pull request merged**
