### PR TITLE
SDK2: remove deprecated securityGroup client

### PR DESCRIPTION
**Pull request by bitoku**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-4665

### What this PR does / why we need it:

This PR updates the deprecated SDK to the new SDK track 2.

### Test plan for issue:

ci, e2e

### Is there any documentation that needs to be updated for this PR?

tech debt cleanup, N/A

### How do you know this will function as expected in production? 

by checking if the cluster deletion succeeded.

### CODE REVIEW

**Review by tiguelu — APPROVED** [review]
LGTM.

Can the old securityGroups file be already removed /ARO-RP/pkg/util/azureclient/mgmt/network/securitygroups.go ?

**Comment by SudoBrendan** [comment]
> LGTM.
> 
> Can the old securityGroups file be already removed /ARO-RP/pkg/util/azureclient/mgmt/network/securitygroups.go ?

The answer is yes - we likely should have held this PR - I didn't have time to review :(

```
$ go mod why github.com/Azure/ARO-RP/pkg/util/azureclient/mgmt/network
# github.com/Azure/ARO-RP/pkg/util/azureclient/mgmt/network
github.com/Azure/ARO-RP/pkg/util/azureclient/mgmt/network
$ go mod why github.com/Azure/ARO-RP/pkg/util/azureclient/mgmt/network
# github.com/Azure/ARO-RP/pkg/util/azureclient/mgmt/network
github.com/Azure/ARO-RP/pkg/util/azureclient/mgmt/network
```

@bitoku can you follow up on this removal and the removal of the dependency entirely from go mod/vendor/etc?

**Comment by bitoku** [comment]
Not yet, there are some other usages. I'm going to follow up them.

**Pull request merged**
