### PR TITLE
Makes test-go fail in case of failure in a pipe

### PR DESCRIPTION
**Pull request by m1kola**

### CODE REVIEW

**Comment by jim-minter** [comment]
failing tests:
`/bin/sh: 1: set: Illegal option -o pipefail`

**Comment by m1kola** [comment]
I think, It happens because we use Ubuntu in CI and it has `dash` shell aliased to `/bin/sh`.

I added `SHELL = /bin/bash` in addition to `pipefail` to see if it helps, but we might need to split `test-go` into more steps (it's quite big already) and have coverage separately.

**Comment by julienstroheker** [comment]
> I think, It happens because we use Ubuntu in CI and it has `dash` shell aliased to `/bin/sh`.
> 
> I added `SHELL = /bin/bash` in addition to `pipefail` to see if it helps, but we might need to split `test-go` into more steps (it's quite big already) and have coverage separately.

Or create a separated `ci` target in the makefile ?

**Comment by jim-minter** [comment]
merging, feel like setting /bin/bash might be better in the CI wrapper though.

**Pull request merged**
