### PR TITLE
fix dev env panic in e2e

### PR DESCRIPTION
**Pull request by bitoku**
### Which issue this PR addresses:

Fixes N/A

### What this PR does / why we need it:

When I ran e2e to the local dev cluster without encryption, I got this error and it panics.

```
  STEP: getting the test cluster resource @ 07/15/24 13:05:49.935
  STEP: checking that disk encryption at rest is enabled for masters @ 07/15/24 13:05:50.148
  [PANICKED] in [It] - /usr/local/Cellar/go/1.22.2/libexec/src/runtime/panic.go:261 @ 07/15/24 13:05:50.148
• [PANICKED] [0.429 seconds]
Disk encryption at rest [It] must be enabled with customer managed key for the cluster and each disk must have it enabled
/Users/atokubi/ARO-RP/test/e2e/disk_encryption.go:70

  [PANICKED] Test Panicked
  In [It] at: /usr/local/Cellar/go/1.22.2/libexec/src/runtime/panic.go:261 @ 07/15/24 13:05:50.148

  runtime error: invalid memory address or nil pointer dereference

  Full Stack Trace
    github.com/Azure/ARO-RP/test/e2e.init.func19.1({0x25a3cc788, 0xc000994270})
    	/Users/atokubi/ARO-RP/test/e2e/disk_encryption.go:85 +0x313
```

The problem is that it tried to dereference `DiskEncryptionSetID` which is nil and it failed.
This PR adds nil check before that not to panic if it is nil.

### Test plan for issue:

Run e2e to a local dev cluster.

### Is there any documentation that needs to be updated for this PR?

e2e bug fix N/A

### How do you know this will function as expected in production? 

Run e2e in CI.

### CODE REVIEW

**Comment by kimorris27** [comment]
I started E2E again because I think the failure was unrelated to your change.

LGTM if E2E passes!

**Review by kimorris27 — APPROVED** [review]
Thanks for the effort put into improving our E2E!

**Review by mociarain — APPROVED** [review]

**Pull request merged**
