### PR TITLE
Install python3 on RP VMs

### PR DESCRIPTION
**Pull request by cadenmarchese**
### Which issue this PR addresses:

Fixes a new dependency on python3 from azure linux extensions.

### What this PR does / why we need it:

Currently, releases are blocked because python3 is not installed on the RP hosts. This installs the package on the host since it's not present by default.

### Test plan for issue:

Test a rollout in canary to confirm functionality.

### CODE REVIEW

**Review by bryanro92 — DISMISSED** [review]

**Review by s-amann — APPROVED** [review]
lgtm

**Review by mwoodson — APPROVED** [review]

**Review by bennerv — COMMENTED** [review]
Do we not need this on the gateway VMs?

**Review by bennerv — CHANGES_REQUESTED** [review]
Please add for `resources_gateway.go` as well.

**Review by s-amann — APPROVED** [review]

**Comment by cadenmarchese** [comment]
The RP python3 change was tested in the most recent Central US EUAP rollout, and it worked. Do we need to do a canary deploy with the gateway change as well?

**Review by bennerv — APPROVED** [review]
lgtm

**Pull request merged**
