### PR TITLE
[ARO-3194] Vendor dnsmasq into the operator

### PR DESCRIPTION
**Pull request by hawkowl**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-3194 

### What this PR does / why we need it:
To remove the installer dependency, we need to vendor in the dnsmasq config code.

### Test plan for issue:

E2E

### Is there any documentation that needs to be updated for this PR?

N/A

### CODE REVIEW

**Review by SudoBrendan — COMMENTED** [review]
To help future reviewers who are a little unfamiliar with where this is coming from, it's basically copy-pasting this file from our vendored installer to remove the dependency: https://github.com/jewzaam/installer-aro/blob/release-4.11-azure/pkg/aro/dnsmasq/dnsmasq.go

There's a few differences with this file here, including the removal of ignition3, which I'm assuming was done because we don't use it here (right?). My biggest concern is how we will keep these files in sync and/or if we need to? Would it be better for us to abstract this away into a 3rd package/repo that is imported by both the installer and the RP so that we prevent drift?

**Comment by tsatam** [comment]
Reviewed, I agree with Brendan's comments. 

I do not believe there to be any practical differences as it stands right now, seeing as the ignition3Config was never used in the result MC, so we should hopefully not have any immediate issues e.g. the installer putting down one version of the MC that then gets replaced by a different one from the operator. This would be of concern if/when more changes are introduced, however.

**Comment by hawkowl** [comment]
Yeah, we don't use ignition3 here, so I removed it.

The work regarding upstream implementation of custom DNS stuff, as well as the ability to "inject" configs and the like into the Installer, will mean that we have to cross the bridge around those differences eventually. Right now, it doesn't particularly matter if the Operator has a different version, as long as *both* versions work.

**Comment by hawkowl** [comment]
@petrkotas this is just a code copy, doesn't change any of the topology or anything :)

**Pull request merged**
