### PR TITLE
Revendor Hive Dependencies - ARO-5061

### PR DESCRIPTION
**Pull request by s-fairchild**
### Which issue this PR addresses:

Fixes
[ARO-5061](https://issues.redhat.com/browse/ARO-5061)

### What this PR does / why we need it:

Revendering Hive Dependencies against hive commit git, commit 83aedb9f6e73f9668a3b96025c97052bfb1e5282, built at 2024-05-10T15:02:58Z

[Reference: Vulnerability Management Plan](https://docs.google.com/spreadsheets/d/14qmjLnW0FdboMzIvXsqSaBYkZgTjK4hH51sXGYgoIxM/edit#gid=0)

### Test plan for issue:

@slawande2 is testing by creating a test cluster in a local full service dev RP.

### Is there any documentation that needs to be updated for this PR?

No.

### CODE REVIEW

**Review by slawande2 — APPROVED** [review]

**Review by cadenmarchese — APPROVED** [review]
/azp run e2e

**Pull request merged**
