### PR TITLE
Removes temporary code which populates createdAt field on cluster docs

### PR DESCRIPTION
**Pull request by m1kola**
### Which issue this PR addresses:

[Work item 9128557](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9128557/)

### What this PR does / why we need it:

It initially was a temporary piece of code. It needs to be removed after running admin updates with #1248 on all regions.

### CODE REVIEW

**Comment by m1kola** [comment]
Rebased

**Comment by jim-minter** [comment]
I don't want to merge this yet because there are some clusters which have not successfully admin updated for a while.

**Comment by jim-minter** [comment]
Marking draft again to avoid inadvertent merge.

**Comment by jim-minter** [comment]
@m1kola please can you close this PR for now?  We don't have a good mechanism in place to decide when we can merge stuff like this, and I think it is a lesser evil to just leave the TODOs in the codebase for now.

**Comment by m1kola** [comment]
@jim-minter I think we are actually very close to merging this. Across all regions we have only 6 cluster in succeeded provisioning state with zero value in the field. More in clusters in failed state, but I think these can be ignored as there is no way to set it for clusters where there is no API server.

Maybe let's keep this PR as a draft and see what happens after the next round of updates?

>  We don't have a good mechanism in place to decide when we can merge stuff like this

I just submitted the PR into ARO-Scripts with the script which counts these clusters.

**Comment by mjudeikis** [comment]
Gonna close as we better do this when we have metrics like this covered. I think we have bigger priorities when to worry about this or any time soon.

**Pull request closed without merging**
