### PR TITLE
Update pull-secret warning.

### PR DESCRIPTION
**Pull request by kwoodson**
An attempt to update the `pull-secret` warning message.

We should come up with a better link that explains the benefits of signing up for Red Hat support.

### CODE REVIEW

**Comment by jim-minter** [comment]
@kwoodson, this was failing CI tests...  I have tried rewording again - does that look better?  I'll open an issue for an aka.ms link later.

**Comment by jim-minter** [comment]
bump @kwoodson please can I have a review on this?

**Comment by kwoodson** [comment]
I'm good with it if you are.  The only thing I think was discussed was putting in a link.  Was that something that you were interested in?

**Comment by jim-minter** [comment]
yes, but we don't have the link yet.  #435 is an issue to remind us to do that when we do.

**Pull request merged**
