### PR TITLE
Removed temporary timestamp update code

### PR DESCRIPTION
**Pull request by bizz001**
### Which issue this PR addresses:

Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9128557

### What this PR does / why we need it:

Removes temporary code responsable of populating `createdAt` field for clusters created before this field was added.

### Test plan for issue:

Functionality removed not added. Removed corresponding unit test.

### Is there any documentation that needs to be updated for this PR?

No. temporary code cleanup.

### CODE REVIEW

**Review by bennerv — DISMISSED** [review]
lgtm - looks like we're all good on clusters according to story notes as well.

**Review by facchettos — APPROVED** [review]
LGTM

**Review by petrkotas — APPROVED** [review]

**Pull request merged**
