### PR TITLE
Add francecentral

### PR DESCRIPTION
**Pull request by Zhuoli**

### CODE REVIEW

**Comment by jim-minter** [comment]
Needs rebase.  To my knowledge the RP is not yet built in francecentral - @mjudeikis

**Comment by mjudeikis** [comment]
@Zhuoli France is not yet built. We planning to build it midd week. Can this wait?

**Comment by Zhuoli** [comment]
Hi @mjudeikis  @jim-minter , could you please make this a high priority?  Here is our PM's reply in verbatim: "If we don’t have it live this week, I suspect we will be at a high risk of losing this customer."

**Comment by Zhuoli** [comment]
> Needs rebase. To my knowledge the RP is not yet built in francecentral - @mjudeikis

Just did rebase, could you take an another look.

**Comment by jim-minter** [comment]
@Zhuoli I have merged francecentral into Arm-Manifests repo in "InProgress" - would you be able to get this manifest deploying in prod, then we can merge this and the RP tests should be green when they run?

**Pull request merged**
