### PR TITLE
apply projectv1.ProjectNodeSelector to namespaces at upgrade

### PR DESCRIPTION
**Pull request by jim-minter**
Follow-on from #887

### CODE REVIEW

**Comment by jim-minter** [comment]
@mjudeikis also this.

**Comment by nilsanderselde** [comment]
This new code in 3 locations is identical, except for the `i` vs. `g` in one place. Could/should this be refactored out into a single function at some point?

**Comment by ehashman** [comment]
@nilsanderselde I believe some of that refactoring is covered in #882

**Pull request merged**
