### PR TITLE
Fix cleaning the gratis subscription

### PR DESCRIPTION
**Pull request by hawkowl**
Fixes subscription cleaning that was broken in #3719

### CODE REVIEW

**Comment by bitoku** [comment]
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=103609613&view=logs&j=a4f1910f-c367-5697-edcd-724d81cde23b&t=bc103e47-9b88-5c56-fcad-f3f2f0b2ed91

Validated the code with this pipeline.

**Review by bitoku — APPROVED** [review]

**Review by kimorris27 — APPROVED** [review]
I'm curious why it broke in the first place, but the fix looks good 👍🏻 

Thanks for the validation @bitoku!

**Comment by bitoku** [comment]
@kimorris27 
The only cause I can think of is https://github.com/Azure/ARO-RP/pull/3823

**Pull request merged**
