### PR TITLE
Verify discovery cache changes in version 4.11.0-rc.4

### PR DESCRIPTION
**Pull request by rhamitarora**
A list of files changed resources between 4.10 and 4.11 when run **make discoverycache**
[Work Item - Verify if DiscoveryCache changes in z-streams will have an effect](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14625899)

### CODE REVIEW

**Review by ross-bryan — CHANGES_REQUESTED** [review]
hey what is this for? we are not on 4.11 and wouldn't add in a release candidate as our version we deploy

**Comment by hawkowl** [comment]
@ross-bryan I asked for a draft PR so that I could see the changes -- if we're going to the RP being multiversion, the discoverycache stuff might be a problem, so this is part of a workitem to see what changes.

**Comment by ross-bryan** [comment]
ack, thx

**Comment by hawkowl** [comment]
Since thi

**Pull request closed without merging**
