### PR TITLE
Fixing bug where incorrect ACR domain name was being generated

### PR DESCRIPTION
**Pull request by SudoBrendan**
### Which issue this PR addresses:

Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13111550/
(ref #1917 point 3)

### What this PR does / why we need it:

Properly generates ACR domain names for fluentbit based on [other configuration](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md#deploying-an-int-like-development-rp)

### Test plan for issue:

N/A - local dev configuration file

### Is there any documentation that needs to be updated for this PR?

N/A

### CODE REVIEW

**Review by bennerv — APPROVED** [review]
lgtm

**Review by bryanro92 — APPROVED** [review]
to me, looks good

**Pull request merged**
