### PR TITLE
Fix CredScan findings in pipeline

### PR DESCRIPTION
**Pull request by cfsmikedrum**
### Which issue this PR addresses:
Fixes CredScan findings in pipeline, where the `Guardian: Post Analysis` task of the `OneBranch-Build and Publish Binary and Container-Official` pipeline shows two CredScan findings.

Link to pipeline run with failed task: https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=51792403&view=logs&j=096205eb-4599-56da-affa-13246cc49eac&t=7e5c3140-9b2b-5395-0e58-9e02fe0de382

### What this PR does / why we need it:
Add two suppression items to the CredScanSuppressions.json file for these files so CredScan will bypass these two findings and not fail the pipeline.

### Test plan for issue:
Changes will be tested after merge to master, as they cannot be tested from a branch.

### Is there any documentation that needs to be updated for this PR?
n/a, as this is part of the standard procedure for CredScan findings

### CODE REVIEW

**Review by bennerv — APPROVED** [review]
LGTM - needed for EV2 public cloud INT run

**Comment by bennerv** [comment]
@bryanro92 can you approve tomorrow so CF can continue with EV2 Int Deploy?

**Review by bryanro92 — APPROVED** [review]
lgtm

**Pull request merged**
