### PR TITLE
Feature/remove enable snapshots feature flag

### PR DESCRIPTION
**Pull request by troy0820**
### Which issue this PR addresses:

Fixes [8267402](https://msazure.visualstudio.com/AzureRedHatOpenShift/_boards/board/t/Red%20Hat%20NASA/Features/?workitem=8267402)

### What this PR does / why we need it:

This removes the feature flag `EnableSnapshots`that is necessary for cluster backups with persisteht volumes.  This will allow everyone to be able to perform cluster backups to include persistent volumes when this is rolled out when this gets merged.

### Test plan for issue:

QE documentation that was written to perform cluster backup with persistent volumes before removing the flag to ensure that the notActions feature works within the denyAssignment to cluster resource group

Performed cluster backup with persistent volumes prior to this PR.  Removed test that would check if subscription was eligible for the preview feature.  

### Is there any documentation that needs to be updated for this PR?

MSFT Documentation will be updated when we roll out to a wider group.

### CODE REVIEW

**Comment by mjudeikis** [comment]
@troy0820 please remove draft and rebase if this is ok to merge

**Comment by ehashman** [comment]
This seems fine to me. Does this successfully update the deny assignments on both cluster create and upgrade?

**Comment by mjudeikis** [comment]
@troy0820 really sorry, I merged things and broke your rebase. Pushed rebased ontop to save you from doing this again :/ sorry

**Review by ehashman — APPROVED** [review]

**Comment by troy0820** [comment]
@ehashman PTAL _(Approval got knocked with rebase)_ 😬

**Review by jim-minter — APPROVED** [review]
lgtm, retriggered unit tests, merge on green

**Pull request merged**
