### PR TITLE
Trim dependency graph by removing unused stuff

### PR DESCRIPTION
**Pull request by petrkotas**
### Which issue this PR addresses:

Fixes none, it is maintanence PR reducing noise in dependency graph

### What this PR does / why we need it:

Removes old unused replace directives.

### CODE REVIEW

**Review by cblecker — APPROVED** [review]

**Review by UlrichSchlueter — APPROVED** [review]
LGTM

**Comment by bennerv** [comment]
@petrkotas any reason /hold is still needed?

**Review by bennerv — APPROVED** [review]
lgtm

**Comment by petrkotas** [comment]
@bennerv Uli wanted to merge after release, jut to be extra safe.

**Comment by bennerv** [comment]
I'm good to merge + remove hold label if you are now.  I think we're well past release + changes here.

**Pull request merged**
