### PR TITLE
Updated rbac-development.json used in setting up a shared rp environment to allow for creating a custom role definition for the first party sub.

### PR DESCRIPTION
**Pull request by coreyperkins**
This allows for injecting a custom role definition (id) for the first party sub when preparing a shared environment to develop against.

### Which issue this PR addresses:

This issue was tracked down by @karanmagdani and it happens when executing the code below during the shared setup process. Note, the usage of "fpRoleDefinitionId"="$(uuidgen)" below was added to allow the role definition to be created.

`LOCATION=eastus
az deployment sub create \
 -l $LOCATION \
 --template-file deploy/rbac-development.json \
 --parameters \
   "armServicePrincipalId=$(az ad sp list --filter "appId eq '$AZURE_ARM_CLIENT_ID'" --query '[].objectId' -o tsv)" \
   "fpServicePrincipalId=$(az ad sp list --filter "appId eq '$AZURE_FP_CLIENT_ID'" --query '[].objectId' -o tsv)" \
   "fpRoleDefinitionId"="$(uuidgen)" \
   "devServicePrincipalId=$(az ad sp list --filter "appId eq '$AZURE_CLIENT_ID'" --query '[].objectId' -o tsv)" \
 >/dev/null`

### What this PR does / why we need it:

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"},{"code":"Forbidden","message":"{\r\n  \"error\": {\r\n    \"code\": \"LinkedAuthorizationFailed\",\r\n    \"message\": \"The client '<user>' with object id '<user oid in aad>' has permission to perform action 'Microsoft.Authorization/roleDefinitions/write' on scope '/subscriptions/26c7e39e-2dfa-4854-90f0-6bc88f7a0fb8'; however, it does not have permission to perform action 'Microsoft.Authorization/roleDefinitions/write' on the linked scope(s) '/subscriptions/46626fc5-476d-41ad-8c76-2ec49c6994eb' or the linked scope(s) are invalid.\"\r\n  }\r\n}"}]}}

### Test plan for issue:

We ran through the process of setting up a shared environment from localhost to an az sub several times to confirm success.

### Is there any documentation that needs to be updated for this PR?

Documentation for this and other items are coming in a PR dedicated to shared rp setup.

Tagging @karanmagdani for further intel and/or approval.

### CODE REVIEW

**Comment by karanmagdani** [comment]
Thanks for the PR @coreyperkins ! LGTM in general 

Just for context for others, the role definition name should be a globally unique identifier (https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/roledefinitions?tabs=bicep#roledefinitions) 

I believe we should remove the defaultValue here as well, but i'll let others chime in and give their thoughts

**Review by karanmagdani — DISMISSED** [review]

**Comment by karanmagdani** [comment]
test comment

**Review by m1kola — DISMISSED** [review]
`deploy/rbac-development.json` is a generated file. Need to update go code which does the generation.

**Review by hawkowl — APPROVED** [review]
This isn't an autogenerated file -- so the changes here are fine.

**Pull request merged**
