### PR TITLE
Set qualys download link config param

### PR DESCRIPTION
**Pull request by bennerv**
### Which issue this PR addresses:

Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15004784

### What this PR does / why we need it:

* Sets the base URL for qualys plugin as it's incorrectly trying to fetch the wrong URL due to a bug in azure-security package.  
* Reverts the previous changes to pinning azure-security to a specific version
* Removes unnecessary parameters we're setting.  They're being unmarshalled into the config struct so we shouldn't have to set them.  

### Test plan for issue:

Full service deploy + deploy to INT.

### CODE REVIEW

**Review by ross-bryan — APPROVED** [review]
LGTM - will approve as is, but one nit on the name of the var - should we consider a prefix with `azSecPack`? like the TenantID?
```
azureSecPackVSATenantId
```
that way we are grouping the vars together for same process and name provides the context they are related

**Review by ross-bryan — DISMISSED** [review]
lgtm thx

**Review by ross-bryan — APPROVED** [review]
lgtm thx

**Comment by bennerv** [comment]
CodeQL is failing after updating it to v2 in #2269 .  Appears to be scanning so many directories that is causing failures in PRs.  There's a new PR #2276 which should fix it, then we can rerun it and merge this in.

**Pull request merged**
