### PR TITLE
Removing the e2e functionality for v4 cleanup

### PR DESCRIPTION
**Pull request by azoppiserpa**
### Which issue this PR addresses:

Fixes JIRA: https://issues.redhat.com/browse/ARO-4222

### What this PR does / why we need it:

The PR intends to retire E2E. This is done by removing the function `createOrUpdateE2EBlob` and its usages.

### Test plan for issue:

Unit tests -> `go test` on `pkg/util/billing` directory passed.
Integration/e2e/other -> to check if applicable.

### Is there any documentation that needs to be updated for this PR?

Yes, the README from `RP-Config`, because we need to remove the E2E storage account parameter, and it is listed on the README. It has been updated on a different PR.

### How do you know this will function as expected in production? 

Will check with my peers throughout their reviews.

### CODE REVIEW

**Comment by kimorris27** [comment]
Hey @azoppiserpa , I don't think E2E is going to run since this PR is from your fork. We have been seeing that the E2E tests that run on PRs from forks will fail even if you run the Azure Pipelines "manually" with a PR comment, and the team likes to see E2E succeed for all PRs.

I think it will be best if you close this PR and open a new PR from a branch that comes directly off of this repository so E2E can run. Feel free to reach out to me in Slack if you have questions!

**Comment by azoppiserpa** [comment]
I see. Thanks @kimorris27, I'll work on that :)

**Comment by azoppiserpa** [comment]
New PR is available now, on branch azoppiserpa/ARO-4222.

https://github.com/Azure/ARO-RP/pull/3494

@kimorris27

**Comment by azoppiserpa** [comment]
Abandoning this pull request as new pull requested was created directly on the repository, following new branch naming conventions.

**Pull request closed without merging**
