### PR TITLE
further env refactoring

### PR DESCRIPTION
**Pull request by jim-minter**
further env refactoring:
* entirely stop using env.Interface outside the core RP codebase
* centralise proxy codebase to share codebase to access clusters
* remove database.Database so that everyone uses their own set of database clients

### CODE REVIEW

**Comment by jim-minter** [comment]
@hawkowl ptal?

**Comment by mjudeikis** [comment]
@jim-minter overall looks ok. database clients does not look nice, but not sure what can be done to keep it simpler :/

**Comment by jim-minter** [comment]
It's green, I'm merging.

**Pull request merged**
