### PR TITLE
Back port v2023-11-22 Azure REST specs 

### PR DESCRIPTION
**Pull request by tony-schndr**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-5599

### What this PR does / why we need it:

This PR back ports changes made to upstream v2023-11-22 Azure REST specs and a handful of additional changes to align ARO-RP REST specs and Azure REST specs.

Changes include:

- Change Provisioning State "Cancelled" -> "Canceled".  This change was required for ARM SignOff to upstream v2023-11-22 to Azure REST Specs.
- Add x-ms-enum header to ProvisioningState and PreconfiguredNSG.  These changes were in Azure REST specs but never made it to ARO-RP during previous API upstreaming.
- Add WorkerProfilesStatus to examples in 2023-11-22.  This was missed when creating v2023-11-22 in ARO-RP.

### Test plan for issue:
Existing CI

### Is there any documentation that needs to be updated for this PR?
NA

### CODE REVIEW

**Review by tsatam — APPROVED** [review]

**Review by jhoreman — APPROVED** [review]
Discussed in team PR meeting. Approved.

**Review by SudoBrendan — APPROVED** [review]

**Pull request merged**
