### PR TITLE
[PIPELINES 1] Move scheduled triggers to yaml pipelines

### PR DESCRIPTION
**Pull request by petrkotas**
### Which issue this PR addresses:

Fixes inconsitency of triggers in pipelines.

### What this PR does / why we need it:

Unifies triggers across UI and YAML pipelines.

Before this PR is merged all triggers from:

- https://msazure.visualstudio.com/AzureRedHatOpenShift/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=135644&view=Tab_Triggers
-  https://msazure.visualstudio.com/AzureRedHatOpenShift/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=135699&view=Tab_Triggers

have to be removed.  After the merge new schedulled runs will be picked up based on YAML schedule.

Signed-off-by: Petr Kotas <pkotas@redhat.com>

### Test plan for issue:

N/A

### Is there any documentation that needs to be updated for this PR?

N/A

### CODE REVIEW

**Review by mjudeikis — CHANGES_REQUESTED** [review]
Approved once yaml linting is fixed and we can merge with pipelines

**Comment by petrkotas** [comment]
Hi @mjudeikis this PR is ready for merge. The UI triggers from 

* https://msazure.visualstudio.com/AzureRedHatOpenShift/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=135644&view=Tab_Triggers
* https://msazure.visualstudio.com/AzureRedHatOpenShift/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=135699&view=Tab_Triggers

have to be removed. After the merge new schedulled runs will be picked up based on YAML schedule.

**Comment by mjudeikis** [comment]
Looks like I can't modify the pipelines for it. @jewzaam can you?

**Comment by hawkowl** [comment]
I can't either. Looks like @jewzaam  will have to

**Review by jewzaam — APPROVED** [review]
UI schedules removed for 2 pipelines linked in PR comments.

**Pull request merged**
