### PR TITLE
Cleanup azureclient

### PR DESCRIPTION
**Pull request by m1kola**
### What this PR does / why we need it:

Cleans up `pkg/util/azureclient`

* Removes unused methods from the interfaces
* Removes unused interfaces/clients
* Standardises methods in `*_addons.go` to use original clients explicitly

### Test plan for issue:

Unit tests and e2e

### Is there any documentation that needs to be updated for this PR?

No, just refactoring.

### CODE REVIEW

**Review by nilsanderselde — COMMENTED** [review]
looks good so far

**Review by petrkotas — DISMISSED** [review]
Thank you for the cleanup. lgtm

**Comment by petrkotas** [comment]
azp run e2e

**Comment by petrkotas** [comment]
There is disk e2e failing, waiting for second run to see if it is related to code change.

**Comment by m1kola** [comment]
There was a conflict. I rebased. Please take another look.

**Review by mjudeikis — APPROVED** [review]

**Pull request merged**
