### PR TITLE
fix API Skeleton file permissions

### PR DESCRIPTION
**Pull request by tony-schndr**
### Which issue this PR addresses:

Fixes file permissions on newly generated API Skeleton

### What this PR does / why we need it:

No changes, just fixes the file permissions on the generated API Skeleton

### CODE REVIEW

**Review by bennerv — APPROVED** [review]
does it make sense to have a test for this so we don't accidentally pr it with wrong permissions in the future?

**Comment by tony-schndr** [comment]
> does it make sense to have a test for this so we don't accidentally pr it with wrong permissions in the future?

I think this makes sense, maybe we can run `make client` and then do the git status check like we do with `make generate`?

**Comment by tony-schndr** [comment]
https://github.com/Azure/ARO-RP/blob/master/.pipelines/ci.yml#L90-L95, we could update `make generate` to `make client`.  `make client` already includes the `generate` target

**Review by petrkotas — APPROVED** [review]
LGTM

**Comment by petrkotas** [comment]
I agree on the check. I will merge this PR, and we add the check in a new PR

**Pull request merged**
