### PR TITLE
Release 4.6.12

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
Waiting for image publishing for E2E to pass

**Comment by mjudeikis** [comment]
> Waiting for image publishing for E2E to pass

Did they changed the image midd release? We had 4.6 published, so what changed?

**Comment by jim-minter** [comment]
> Did they changed the image midd release? We had 4.6 published, so what changed?

@mjudeikis see https://github.com/openshift/installer/pull/4422 .  Nothing looked critical for us, but I figured I'd pull it in nonetheless.

**Comment by jim-minter** [comment]
Merge after the next RP rollout.

**Comment by hawkowl** [comment]
:+1:

**Review by mjudeikis — APPROVED** [review]
:fire: :100: :1st_place_medal:

**Comment by jim-minter** [comment]
:fireworks:

**Pull request merged**
