### PR TITLE
Add toggle to build fluentbit

### PR DESCRIPTION
**Pull request by mikeandescavage**
### Which issue this PR addresses:

Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10157198

### What this PR does / why we need it:

This allows a user to decide if they want to build the fluentbit container during the bootstrapping pipeline.  It defaults to false and will skip building.

Versioning will remain in the pipeline template to require peer reviews.

### Test plan for issue:

https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=44742337&view=results (With Fluentbit)
https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=44741921&view=results (Without Fluentbit)

### Is there any documentation that needs to be updated for this PR?

No

**NOTE**: const.go is still hardcoded for version 1.7.8-1.  While that exists in our local ACRs, updating that file is outside of the scope of this pipeline work.

### CODE REVIEW

**Comment by m1kola** [comment]
> Requiring a user to provide a version allows this pipeline to run without the need of submitting future PRs to have a newer version to be built and then pushed to our local ACR.

But the downside is that now we have to go and find the version number to be able to run the pipeline. And we need to manually pick the correct one.

Sounds like having to subbmit a PR with a new version is less error prone process than the above.

Or do I miss something?

**Review by jewzaam — CHANGES_REQUESTED** [review]
If we run the bootstrap pipeline it's not likely for fluentbit.  Requiring this for every run is going to be error prone.  Given we only need to build this periodically I recommend we make it optional.  Could we have the absence of tdAgentVersion skip building fluentbit?

Also need docs on how to run this somewhere including how to find a valid version.  This is a gap we have today.

**Review by jewzaam — APPROVED** [review]
Added a FAQ in ADO that covers the documentation request here.

**Comment by jewzaam** [comment]
https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/172367/FAQ-ARO-in-Fairfax

**Pull request merged**
