### PR TITLE
Remove SDN option from the stable API

### PR DESCRIPTION
**Pull request by cblecker**
### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

This is a near revert of #2241, which added selecting SDN as an option to the stable API

### CODE REVIEW

**Review by bennerv — COMMENTED** [review]
Why are there file extensions with `.go-e`?

Additionally, we must follow Azure's [deprecation policy](https://eng.ms/docs/products/arm/api_contracts/apideprecationpolicy) on removing our 2021-09-01 preview API which currently supports setting the SDN. 

Since it was a preview API, we're not subject to the 36 month notice we would have had to give customers, just 90 days.

**Comment by cblecker** [comment]
@bennerv
Not looking at removing from the preview API right now, just removing from the stable API.

As for `.go-e`, these were generated by autorest. I just ran a `make client`.

**Comment by bennerv** [comment]
> @bennerv Not looking at removing from the preview API right now, just removing from the stable API.
> 
> As for `.go-e`, these were generated by autorest. I just ran a `make client`.

That's weird.  It should generate `.go` files.  You can't remove it from existing APIs though so any modifications to files non-2022-09-04 are not good.

**Comment by cblecker** [comment]
The new go-e files were the only ones changing for the other API versions. I removed them from the commit.

**Review by ross-bryan — APPROVED** [review]
lgtm

**Review by bennerv — APPROVED** [review]

**Pull request merged**
