### PR TITLE
Delete VMs before other resources

### PR DESCRIPTION
**Pull request by jim-minter**
1. Delete VMs before other resources.
2. Delete all resources before deleting the RG, this is to try to help periodic problems that we see where RG deletions take forever.
3. Looked into an "increase internetreachable test timeout for worker" flake - the workers were rotating and the
operator was being rescheduled between them.  Bumping the timeout for now.

### CODE REVIEW

**Comment by jim-minter** [comment]
@hawkowl ptal.  I fast-tracked doing this because we're getting lots of e2e failures with deletions and I wanted this code to try to work around it.

**Review by mjudeikis — APPROVED** [review]
With condition that ordering code gets more comments :)

**Pull request merged**
