### PR TITLE
Update azure-sdk-for-go/sdk/azidentity for WI/MI compatibility

### PR DESCRIPTION
**Pull request by kimorris27**
### Which issue this PR addresses:

https://issues.redhat.com/browse/ARO-3986

### What this PR does / why we need it:

Updates `azidentity` and `azidext` for compatibility with workload identities.

I initially just updated `azidentity`, but my local RP was erroring out saying the `Authorization` header wasn't getting set on the RP's requests to Azure:

```
(aro-dev) ➜ ~/go/src/github.com/Azure/ARO-RP (update-azure-sdk-for-go/sdk/azidentity) ✗ make runlocal-rp
go run -ldflags "-X github.com/Azure/ARO-RP/pkg/util/version.GitCommit=db0b249-dirty" ./cmd/aro rp
INFO[2023-08-25T10:30:11-05:00]cmd/aro/main.go:51 main.main() starting, git commit db0b249-dirty           
INFO[2023-08-25T10:30:11-05:00]pkg/env/core.go:63 env.NewCore() running in local development mode            
INFO[2023-08-25T10:30:11-05:00]pkg/util/instancemetadata/instancemetadata.go:60 instancemetadata.New() creating development InstanceMetadata        
INFO[2023-08-25T10:30:11-05:00]pkg/env/core.go:71 env.NewCore() InstanceMetadata: running on AzurePublicCloud 
FATA[2023-08-25T10:30:12-05:00]cmd/aro/main.go:88 main.main() compute.ResourceSkusClient#List: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing." 
exit status 1
make: *** [runlocal-rp] Error 1
```

I traced this issue to `azidext` and found that updating `azidext` did the trick. See the commit message on my first commit on this branch for more context.

### Test plan for issue:

- Created and deleted a cluster using my local RP to verify RP Azure authentication
- E2E to catch things my simple local test wouldn't have

### Is there any documentation that needs to be updated for this PR?

No

### CODE REVIEW

**Comment by kimorris27** [comment]
I've made an additional commit to fix some broken unit tests. I ended up removing part of the tests. See the commit message for details.

**Comment by cadenmarchese** [comment]
This looks good to me. Here are some potential other testing ideas we may want to do (outside of a release):
- INT deploy + at least one create / delete
- Partial prod deploy (canary, and potentially pilot)

Any thoughts / do you think it's necessary?

**Comment by kimorris27** [comment]
> This looks good to me. Here are some potential other testing ideas we may want to do (outside of a release):
> 
> * INT deploy + at least one create / delete
> * Partial prod deploy (canary, and potentially pilot)
> 
> Any thoughts / do you think it's necessary?

Updating all of these Azure packages is a big enough deal that it's probably worth doing one of those. How about I do a canary deploy with a create and delete?

**Comment by hawkowl** [comment]
I'm honestly happy merging this since we can back it out if those problems do occur.

**Review by hawkowl — APPROVED** [review]

**Pull request merged**
