### PR TITLE
Bug fix - Add nil pointer check for LoadBalancerProfile in cluster metrics

### PR DESCRIPTION
**Pull request by s-fairchild**
### Which issue this PR addresses:

[ARO-9146](https://issues.redhat.com/browse/ARO-9146)

Fixes

### What this PR does / why we need it:

If the `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile ` is nil, checking for a nil `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile.ManagedOutboundIPs` will cause a panic.
Relevant line from stack trace:
```go
(*openShiftClusterBackend).gatherNetworkMetrics(0xc000a0cff0, 0x5c35fa0?, 0xc00109c600, 0x6?)\n\t/app/pkg/backend/metrics.go:221 +0x930\ngithub.com/Azure/ARO-RP/pkg/backend.
```

Checking for `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile` first will stop a nil `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile.ManagedOutboundIPs` from being de referenced.

### Test plan for issue:

Covered by unit tests.
Will also create a UDR cluster with this document: https://github.com/Azure/ARO-RP/blob/master/docs/deploy-development-rp.md#run-the-rp-and-create-a-cluster

### Is there any documentation that needs to be updated for this PR?

No.

### How do you know this will function as expected in production?

Unit tests added pass a nil LoadBalancerProfile on this branch, while causing a panic on master.

### CODE REVIEW

**Review by tsatam — APPROVED** [review]
LGTM. It doesn't need to be done immediately within this PR, but as soon as we can, we should introduce a panic guard within this metrics function so that future nil pointer dereferences or other panics cannot halt execution on the backend.

**Review by cadenmarchese — APPROVED** [review]

**Review by kimorris27 — APPROVED** [review]

**Review by jhoreman — APPROVED** [review]
Approved, thanks for this!

**Review by SrinivasAtmakuri — APPROVED** [review]
LGTM!

**Pull request merged**
