### PR TITLE
Update changes required for Microsoft Graph

### PR DESCRIPTION
**Pull request by nontw**
### Which issue this PR addresses:

#2168 

### What this PR does / why we need it:

Apply changes required for MS Graph.  These commands are currently failing because they refer to a now nonexistent field name.

### Test plan for issue:

Tested by rebuilding the local RP.  The rebuild was successful.

### Is there any documentation that needs to be updated for this PR?

Docs update are included.

### CODE REVIEW

**Review by s-amann — APPROVED** [review]

**Review by SudoBrendan — APPROVED** [review]
LGTM

**Review by karanmagdani — APPROVED** [review]
Thanks for this PR! LGTM. 

This would also affect some of our docs related to Service Principals. Are there plans to make changes there as well?  https://docs.microsoft.com/en-us/azure/openshift/howto-service-principal-credential-rotation#user-provided-client-id-and-client-secret-service-principal-credential-rotation-

**Comment by nontw** [comment]
@karanmagdani so sorry didn't come to look if there was any reply... Anyway, I think the doc you mentioned doesn't need to be updated.  From the published breaking changes, `az ad sp reset` was changed, but the way the second command in the doc is not affected by them.  

https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration#az-ad-sp-credential-reset

Anything related to `az aro` has been handled by a different PR and didn't introduce any breaking changes to the customer. 

Let me know if you have more questions.

**Review by karanmagdani — APPROVED** [review]

**Review by ross-bryan — APPROVED** [review]
lgtm

**Pull request merged**
