### PR TITLE
Add NRMS/Hypernet tags to cluster resource group in CI mode

### PR DESCRIPTION
**Pull request by cadenmarchese**
### Which issue this PR addresses:

The RP fails cluster installs if NSGs are attached to subnets. Simply Secure v1 applies NSGs in our subscriptions when these tags aren't present, resulting in a race condition.

### What this PR does / why we need it:

Adds the tags needed to stop SSv1 from applying NSGs to subnets: https://eng.ms/docs/security-compliance-identity-and-management-scim/security/azure-security/security-health-analytics/network-isolation/netiso-teamdocs/netiso-program-overview/manage/hypernet-and-nrms-simply-secure-v1-network-security-rules

### Test plan for issue:

Deploy this commit to central us euap (where the issue is faced)

### Is there any documentation that needs to be updated for this PR?

No

### CODE REVIEW

**Review by s-amann — DISMISSED** [review]

**Review by rogbas — DISMISSED** [review]
LGTM

**Comment by cadenmarchese** [comment]
`hold` for now as tagging the resource group didn't have the desired effect. We'll need to update these tags with a temporary SSv1 exception number and re-test.

**Review by ross-bryan — COMMENTED** [review]
We need to get an exception from microsoft, I understand this code was for testing purposes but it should not make it into production.

**Comment by cadenmarchese** [comment]
@ross-bryan we can open a new PR with exception tags later if needed. Closing this one.

**Pull request closed without merging**
