### PR TITLE
Don't scan generated code for CodeQL

### PR DESCRIPTION
**Pull request by hawkowl**
We shouldn't scan this, because it's useless and doesn't give us useful information + takes longer.

### CODE REVIEW

**Comment by hawkowl** [comment]
@tsatam Because it does a build and checks the compiled binary, that all works. The go config in there is basically because it needs to exist for the matrix, it doesn't effectively do anything.

**Review by yjst2012 — APPROVED** [review]
looks good to me, just not sure if we want to ignore the vendor folder as well as Tanmay suggested?

**Comment by hawkowl** [comment]
@yjst2012 You can't ignore dirs for compiled code, so it wouldn't do anything. The existing ones there don't really do much either :)

**Pull request merged**
