### PR TITLE
Update controllergen commands to work with 0.9.0

### PR DESCRIPTION
**Pull request by hawkowl**
### Which issue this PR addresses:
fixes a local build failure

### What this PR does / why we need it:

Right now we rely on controller-gen 0.5.0, which is old and gives the wrong version when we run with `go run tool@version`. So, we should update it to 0.9.0 (which is current).

### Test plan for issue:
CI/E2E

### Is there any documentation that needs to be updated for this PR?
N/A

### How do you know this will function as expected in production? 

E2E

### CODE REVIEW

**Comment by bitoku** [comment]
> fixes a local build failure

What error did you get?

**Comment by hawkowl** [comment]
@bitoku Running it with the real v0.5.0 outside of vendoring causes it to change the version number to the correct v0.5.0, and using the v0.9.0 that it reports causes another diff of newlines. This is because the v0.5.0 we're using misreports itself as v0.9.0 as per the `go.mod` before overrides.

**Review by mociarain — APPROVED** [review]
LGTM

**Pull request merged**
