### PR TITLE
Split k8s and az actions

### PR DESCRIPTION
**Pull request by nilsanderselde**
### Which issue this PR addresses:

Fixes https://github.com/Azure/ARO-RP/issues/1061

### What this PR does / why we need it:

Currently, all admin actions only work if k8s clients can be created, even if they don't require the use of k8s clients. In clusters that failed to be created, this may not be the case. If they don't have a value for `PrivateEndpointIP`, restconfig cannot be created. Therefore, the k8s clients can't be created, either. This PR enables us to do things like list Azure resources even if the k8s clients can't be created, which would help debug some failed cluster creations.

### Test plan for issue:

Run existing unit and E2E tests

### Is there any documentation that needs to be updated for this PR?

No.

### CODE REVIEW

**Comment by jim-minter** [comment]
Aren't Azure geneva actions and k8s geneva actions completely disjoint?
Please could you see if you can separate them so that each is off a separate struct?

**Comment by nilsanderselde** [comment]
E2E failed with
```
unknown blob
make: *** [publish-image-aro] Error 1
```

**Review by jim-minter — APPROVED** [review]
LGTM.  Un-draft it if you want it merged now.

**Review by mjudeikis — APPROVED** [review]

**Pull request merged**
