### PR TITLE
Add maintenance state for customer action needed

### PR DESCRIPTION
**Pull request by niontive**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-4365

### What this PR does / why we need it:

If a maintenance operation fails, we may need the customer to take action. We will notify the customer via a resource health check signal. 

This PR implements a new signal to tell the customer to take action. This PR implements arrows 11, 12 and 13 in [this diagram](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/AzureRedHatOpenShift.wiki/595193/Maintenance-Signals-State-Diagram?anchor=new-state-diagram).

### Test plan for issue:

- Unit tests
- Test in INT

### Is there any documentation that needs to be updated for this PR?

See above diagram link

### CODE REVIEW

**Review by bbethell-1 — COMMENTED** [review]
LGTM

**Comment by niontive** [comment]
Code Review December 13th:

- Verify if we need code to reject transition from customer action needed to maintenance ongoing. This prevents us from accidentally from running maintenance on a cluster that has failed + needs customer action

**Comment by niontive** [comment]
Reviewed with @bennerv and @SudoBrendan.  We'll not support blocking transition from "customer action needed" to "maintenance ongoing." No code changes needed - code as is supports this.

**Review by bennerv — APPROVED** [review]
lgtm

**Review by s-amann — APPROVED** [review]

**Review by cadenmarchese — APPROVED** [review]

**Pull request merged**
