### PR TITLE
Add preview API to ARO-RP

### PR DESCRIPTION
**Pull request by petrkotas**
### Which issue this PR addresses:

Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7508558

### What this PR does / why we need it:

Introduce preview API for ARO-RP. This enables adding new features exposed via API.

### Test plan for issue:

Currently, the API is the same as released stable API v20200430. No tests are included at this time.

### Is there any documentation that needs to be updated for this PR?

No documentation yet, as this API is a plain copy of stable API.

### CODE REVIEW

**Comment by ehashman** [comment]
@petrkotas I'd like to spend a little bit of time thinking about this, to avoid copy-pasting code as much as we did in v3.

It looks to me like a lot of this is repeated between the swagger definitions and the Go implementation. Is there any way that we could e.g. use code generation to make this a bit more DRY?

@mjudeikis is there a design doc for the new API and adding APIs going forward for the team to review?

**Comment by mjudeikis** [comment]
> @petrkotas I'd like to spend a little bit of time thinking about this, to avoid copy-pasting code as much as we did in v3.
> 
> It looks to me like a lot of this is repeated between the swagger definitions and the Go implementation. Is there any way that we could e.g. use code generation to make this a bit more DRY?

At that point you see we could use code generation? repetition is because we generate swagger already. 
> 
> @mjudeikis is there a design doc for the new API and adding APIs going forward for the team to review?

There is no design as this is all boilerplate. Everything is in the stories in the epic `New ARO API (2020-xx-yy-preview)`

**Comment by petrkotas** [comment]
I have tested the api and it creates the cluster fine. No errors.

**Comment by ad-m** [comment]
@petrkotas, I am glad to hear that.

**Pull request merged**
