### PR TITLE
Update role definition names and keys used for MIWI

### PR DESCRIPTION
**Pull request by bennerv**
### Which issue this PR addresses:
Role definition names after feedback and more [explicit role names](https://docs.google.com/spreadsheets/d/1D2o6Wi54yq75SLfIkP5wIMRamwre7pVDO9eJpCXRhXI/edit?gid=0#gid=0).

### What this PR does / why we need it:
Role definition names after feedback and more explicit role names.

### Test plan for issue:

N/A

### CODE REVIEW

**Review by tsatam — DISMISSED** [review]
LGTM

**Review by cadenmarchese — CHANGES_REQUESTED** [review]
Can we also update the roleset in pkg/util? 

https://github.com/Azure/ARO-RP/blob/master/pkg/util/rolesets/const.go

**Comment by bennerv** [comment]
>Can we also update the roleset in pkg/util?

Why is it defined in two places?  (actually three, RP config too).

**Comment by kimorris27** [comment]
> > Can we also update the roleset in pkg/util?
> 
> Why is it defined in two places? (actually three, RP config too).

It looks like the `pkg/util/rolesets/const.go` one is only referenced by the dev cluster hack: https://github.com/Azure/ARO-RP/blob/3b6426c8c155e1ec76e09ab47ef1f410412fa7b1/pkg/util/cluster/cluster.go#L702

The hack could probably read it from the env var to knock it down from three places to two.

**Review by kimorris27 — APPROVED** [review]

**Pull request merged**
