### PR TITLE
Use newer default Kubernetes version

### PR DESCRIPTION
**Pull request by razo7**
While trying to deploy AKS on step 8 as mentioned in https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md, I got an error from the default Kubernetes version which is not supported (and not modified in run time).

**The suggested fix is a workaround.**

### Which issue this PR addresses:

Fixes a possible bug when using `deploy_aks_dev` function from _hack/devtools/deploy-shared-env.sh_

### What this PR does / why we need it:

Update the default Kubernetes version as it was asked by the `deploy_aks_dev` function from _hack/devtools/deploy-shared-env.sh_. 
Error :
```
➜  ARO-RP git:(master) deploy_aks_dev
########## Deploying aks-development in RG root-aro-eastus ##########
ERROR: {"code": "InvalidTemplateDeployment", "message": "The template deployment 'aks-development' is not valid according to the validation procedure. The tracking id is 'b57d1c7e-dd25-44a9-998c-51915fb7738e'. See inner errors for details."}

Inner Errors: 
{"code": "AgentPoolK8sVersionNotSupported", "message": "Preflight validation check for resource(s) for container service aro-aks-cluster-001 in resource group root-aro-eastus failed. Message: Version 1.26.6 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list. Details: "}
```

The desired fix helped to deploy aks, while the supported versions were:

```
➜  ARO-RP git:(master) az aks get-versions -l $LOCATION
{
  "values": [
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isDefault": true,
      "isPreview": null,
      "patchVersions": {
        "1.28.5": {
          "upgrades": [
            "1.28.9",
            "1.29.4",
            "1.29.2"
          ]
        },
        "1.28.9": {
          "upgrades": [
            "1.29.4",
            "1.29.2"
          ]
        }
      },
      "version": "1.28"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial",
          "AKSLongTermSupport"
        ]
      },
      "isDefault": null,
      "isPreview": null,
      "patchVersions": {
        "1.27.7": {
          "upgrades": [
            "1.27.9",
            "1.28.9",
            "1.28.5"
          ]
        },
        "1.27.9": {
          "upgrades": [
            "1.28.9",
            "1.28.5"
          ]
        }
      },
      "version": "1.27"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isDefault": null,
      "isPreview": null,
      "patchVersions": {
        "1.29.2": {
          "upgrades": [
            "1.29.4"
          ]
        },
        "1.29.4": {
          "upgrades": []
        }
      },
      "version": "1.29"
    }
  ]
}

```

### CODE REVIEW

**Review by tiguelu — APPROVED** [review]
Just for the record, we're currently using older than 1.29 in INT, and our shared dev envs seem to be using even older than INT (so we're not consistently updating our dev envs). Having this var updated to a more recent new version for new shared dev environments seems like a good idea to me.

**Review by hlipsig — APPROVED** [review]
Will make development efforts easier so this makes sense to me.

**Review by jaitaiwan — APPROVED** [review]
LGTM, appreciated the detailed explanation of why in the description.

**Review by tiguelu — APPROVED** [review]

**Pull request merged**
