### PR TITLE
Bump versions of MDM + MDSD to latest

### PR DESCRIPTION
**Pull request by hawkowl**
### Which issue this PR addresses:

Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10409039

### What this PR does / why we need it:

Bumps tags of MDM + MDSD

### Test plan for issue:

Should be covered by E2E?

### Is there any documentation that needs to be updated for this PR?

N/A

### CODE REVIEW

**Review by mjudeikis — APPROVED** [review]

**Comment by jewzaam** [comment]
CI failing for https://github.com/Azure/azure-cli/issues/18950

**Review by troy0820 — CHANGES_REQUESTED** [review]
`make generate` from golang unit test errors.

**Review by jewzaam — CHANGES_REQUESTED** [review]
Upstream CI issue is mitigated, please rebase.

**Comment by jewzaam** [comment]
Closing in favor of https://github.com/Azure/ARO-RP/pull/1644 where it's rebased and `make generate` is run.

**Pull request closed without merging**
