### PR TITLE
OneBranch Pipeline for Kusto Cluster Deployments

### PR DESCRIPTION
**Pull request by zacharyljones**
**What this PR does / why we need it**:

Creates a OneBranch pipeline for generating and deploying Kusto Ev2 config files

**Relevant work item**:
[Deploy Kusto Cluster to Public INT](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/10097594)

**Test plan for issue:**

OneBranch build pipeline is already deploying Kusto clusters to public INT from fork. Build pipeline will be modified to target this main repo.

**Is there any documentation that needs to be updated for this PR?**

No

### CODE REVIEW

**Comment by mjudeikis** [comment]
@jewzaam Im big far from all EV2 pipelines so will leave it for you. No idea what and how this gonna work :/

**Comment by jewzaam** [comment]
@zacharyljones what is the state of this work?  Seems incomplete, doesn't do anything for generationType = kusto.  The bash script referenced is basically empty as well in the ADO repo.

**Review by jewzaam — APPROVED** [review]

**Pull request merged**
