### PR TITLE
ARO-6756 Remove usecheckaccess feature and environment variables

### PR DESCRIPTION
**Pull request by rajdeepc2792**
### Which issue this PR addresses:
Additional changes for
https://issues.redhat.com/browse/ARO-6756

Additional PRs:-
https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO-Pipelines/pullrequest/10341885
https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/RP-Config/pullrequest/10341820

It just removes the feature and related environment variables, doesn't change the implementation as the checkAccessV2 is used for all the environments after https://github.com/Azure/ARO-RP/pull/3524

### What this PR does / why we need it:

Since CheckAccessV2 is now available and running in all the environments, no feature variable is needed for CheckAccessV2

### Test plan for issue:

-> Updated Unit Tests where checkaccessv2 variable was used.
-> Pass all the unit test cases
-> Pass e2e

### Is there any documentation that needs to be updated for this PR?
Document already exists for CheckAccessV2 in ADO:- https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/AzureRedHatOpenShift.wiki/409184/CheckAccess-API-migration

The document will be updated with the getAccess marked as deprecated once the changes are merged and available in production.

### How do you know this will function as expected in production? 
Currently, the production/Local Dev/Full RP already relies on CheckAccessV2, so no functionality change from that point of view.

### CODE REVIEW

**Review by cadenmarchese — APPROVED** [review]

**Review by kimorris27 — COMMENTED** [review]
LGTM if E2E passes!

**Review by kimorris27 — APPROVED** [review]

**Review by cadenmarchese — APPROVED** [review]
lgtm! thanks for the cleanup.

**Review by kimorris27 — APPROVED** [review]

**Pull request merged**
