### PR TITLE
rebase from az downstream

### PR DESCRIPTION
**Pull request by mjudeikis**
rebase from https://github.com/Azure/azure-cli/commit/fd6af4966e350e25d9398b471c3e19ee57e5ab57

### CODE REVIEW

**Comment by jim-minter** [comment]
The intention of this is to minimise the delta between us and the official repo?  Were these files generated from our repo code or copied?  How do we keep them up to date?

**Comment by m1kola** [comment]
I was wondering if we can change the process to avoid having two copies of aro command, but keep the benefits of being able to make changes to the client and integrate quickly.

The reason is that we will soon have more PRs similar to this one. For example, I'll soon need to submit one to reflect changes from https://github.com/Azure/azure-cli/pull/13066.

**Comment by m1kola** [comment]
Just to clarify: I'm not saying that we should solve it in this PR, but something to think of.

**Comment by mjudeikis** [comment]
> The intention of this is to minimise the delta between us and the official repo? Were these files generated from our repo code or copied? How do we keep them up to date?

We should be running those on our repo. But in this case upstream fixed them on their own so we re-aligning.

**Comment by m1kola** [comment]
@mjudeikis could you please update the PR again to include changes from https://github.com/Azure/azure-cli/pull/13066?

We already have changes in `aro/_format.py` in our repo, but there are new recordings and some changes in tests.

**Comment by jim-minter** [comment]
We've got a long PR list and this PR does not seem close to mergeable.  Please can you ensure there is an issue to track the work and close this for now?

**Pull request closed without merging**
