### PR TITLE
pinning the RHEL version due to missing RHUI repositories.

### PR DESCRIPTION
**Pull request by Makdaam**
Pinning RHEL 7 version in RP VMs due to RHUI repositories not being in the "latest" config.

### CODE REVIEW

**Comment by jim-minter** [comment]
force pushed rebase to fix conflict

**Comment by jim-minter** [comment]
@Makdaam @mjudeikis I have created a new branch https://github.com/Azure/ARO-RP/tree/hotfix-20201112 with this change.

**Comment by jim-minter** [comment]
@Makdaam please close this PR and reopen it to merge to master

**Comment by Makdaam** [comment]
https://github.com/Azure/ARO-RP/pull/1151/files opened to merge to master.

**Pull request closed without merging**
