### PR TITLE
Disable cosmosdb local auth

### PR DESCRIPTION
**Pull request by sankur-codes**
### Which issue this PR addresses:

Fixes [ARO-5514](https://issues.redhat.com/browse/ARO-5514)

### What this PR does / why we need it:

This PR will disable local authentication on CosmosDB to force use of managed identities for the same implemented under  [ARO-7195](https://issues.redhat.com/browse/ARO-7195).

### Test plan for issue:

NA

### Is there any documentation that needs to be updated for this PR?

NA

### How do you know this will function as expected in production? 

NA

### CODE REVIEW

**Review by SudoBrendan — APPROVED** [review]

**Review by anshulvermapatel — APPROVED** [review]

**Review by bennerv — COMMENTED** [review]
lgtm, but how are we retrofitting all our environments? 

Have we manually updated role assignments on the aro service principals in all environments?  Who's expected to make the change to the existing coosmosdb instances.

**Comment by weinong** [comment]
@bennerv my understanding is that ARO RP already uses MSI to access cosmosDB. The only thing that didn't was billing which got updated to use MSI in August.

**Comment by weinong** [comment]
https://github.com/Azure/ARO-RP/blob/master/pkg/database/fromenv.go#L25-L36

**Comment by bennerv** [comment]
> @bennerv my understanding is that ARO RP already uses MSI to access cosmosDB. The only thing that didn't was billing which got updated to use MSI in August.

I thought we had a few cosmosdb instances hanging around that we missing permissions in our local dev.  It's possible we still do, and we'll need to retrofit them to work and probably disable local auth on them.  We should also remove usages of master key authorizers because it will no longer work with this change.  

i'm fine with it now though because everything should mostly be in place.

**Review by bennerv — APPROVED** [review]

**Pull request merged**
