### PR TITLE
Revendor go-cosmosdb

### PR DESCRIPTION
**Pull request by tsatam**
### Which issue this PR addresses:

Fixes [ARO-6247](https://issues.redhat.com/browse/ARO-6247)

### What this PR does / why we need it:

- Vendors in newest version of go-cosmosdb client that includes this fix: https://github.com/jewzaam/go-cosmosdb/pull/21 
  - necessary to avoid a JSON decode error that occurs on Go 1.20+ due to the following issue: https://github.com/ugorji/go/issues/388 
- Regenerates client to include new MissingFields implementation on PartitionKeyRange
  - fixes another non-fatal json decode error noticed during RP execution

### Test plan for issue:

- [ ] TODO: validate E2E passes

### Is there any documentation that needs to be updated for this PR?

No

### How do you know this will function as expected in production? 

We will need to observe logs for the monitor and gateway components in pre-production regions for releases containing this fix and built against Go 1.20+, to ensure that there are no fatal json decode errors occurring in those components.

### CODE REVIEW

**Review by bennerv — APPROVED** [review]
lgtm

**Review by SudoBrendan — APPROVED** [review]

**Review by mociarain — APPROVED** [review]
LGTM

**Review by kimorris27 — APPROVED** [review]

**Comment by tsatam** [comment]
Closing in favor of #3474, which is identical but from a branch on this upstream repo to get e2e checks

**Pull request closed without merging**
