### PR TITLE
ARO-5325: Propagate install error to user

### PR DESCRIPTION
**Pull request by edisonLcardenas**
### Which issue this PR addresses:

Fixes
https://issues.redhat.com/browse/ARO-5325

### What this PR does / why we need it:
Propagate error to user.

### Test plan for issue:
Updated runner_test.go 

### Is there any documentation that needs to be updated for this PR?

No, tech debt.

### How do you know this will function as expected in production? 
Unit test.

### CODE REVIEW

**Review by kimorris27 — APPROVED** [review]

**Comment by LiniSusan** [comment]
@edisonLcardenas : will these changes take the error to frontend (to user)??

**Comment by rhamitarora** [comment]
LGTM

**Review by rhamitarora — APPROVED** [review]

**Comment by rajdeepc2792** [comment]
LGTM

**Review by anshulvermapatel — APPROVED** [review]

**Pull request merged**
