### PR TITLE
Commit to allow password auth for VMSS jit access

### PR DESCRIPTION
**Pull request by jhoreman**
### Which issue this PR addresses:

13498318 SPIKE: Change the way in which we SSH to RP/Gateway VM Instances in Prod
Fixes

### What this PR does / why we need it:
This will allow ARO SRE to properly control SSH access to VMSS (Gateway and RP) through approved JIT processes and forego the use of a shared private key. 

### Test plan for issue:

Request VMSS jit according to SOP (see below) and access VM from SAW VPN. 

### Is there any documentation that needs to be updated for this PR?

Yes, SOP and documentation pending.

### CODE REVIEW

**Review by bennerv — COMMENTED** [review]
/hold on documentation for accessing VMs via existing JIT action.  

Couple questions though
1. Can we remove the SSH public keys now too (so we don't have a 'backdoor' to get the RP)?
2. How will we access INT/Dev VMs?  Can we still use some form of JIT?

**Comment by jhoreman** [comment]
> /hold on documentation for accessing VMs via existing JIT action.
> 
> Couple questions though
> 
>     1. Can we remove the SSH public keys now too (so we don't have a 'backdoor' to get the RP)?
> 
>     2. How will we access INT/Dev VMs?  Can we still use some form of JIT?

SOP/Docs here:

https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/235246/JIT-VMSS-SSH-Access

>     1. Can we remove the SSH public keys now too (so we don't have a 'backdoor' to get the RP)?

A: This would be preferred. I would allow for some overlap between the two access methods for some time, but ultimately once this process has been accepted we would no longer have a need for a shared key pair. 

>     2. How will we access INT/Dev VMs? Can we still use some form of JIT?

I do not believe DEV/INT have JIT access portals. We may need to leverage some type of direct access through the Azure portal for these.

**Review by bryanro92 — COMMENTED** [review]
LGTM, straight forward change, i'd just like to touch base with our microsoft friends and make sure they don't have any issues with this architectural change

**Review by s-amann — APPROVED** [review]
lgtm, ssh all the RP!

**Comment by jhoreman** [comment]
> LGTM, straight forward change, i'd just like to touch base with our microsoft friends and make sure they don't have any issues with this architectural change

Additional confirmation would be good. FWIW I ran this by the MSFT JIT team and this logically follows their design philosophy around this specific JIT action.

**Review by karanmagdani — COMMENTED** [review]
Thanks for this PR. just a comment, i noticed there is a deny policy on such actions, as far as i understand, it is not applied by default and we actually have to go in and create it. Can we confirm this with MSFT if possible? https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/eliminate-password-based-attacks-on-azure-linux-vms/ba-p/2271139

**Comment by jhoreman** [comment]
> Thanks for this PR. just a comment, i noticed there is a deny policy on such actions, as far as i understand, it is not applied by default and we actually have to go in and create it. Should we confirm this with MSFT ? https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/eliminate-password-based-attacks-on-azure-linux-vms/ba-p/2271139

Hey Karan, I believe this policy is not applied by default and we do not leverage it. This account creation happens through the waagent backplane and was successful in testing only by allowing password authentication.

**Review by bryanro92 — APPROVED** [review]

**Comment by bryanro92** [comment]
approved, but please rebase

**Review by SudoBrendan — APPROVED** [review]
LGTM

**Review by bennerv — APPROVED** [review]

**Pull request merged**
