### PR TITLE
Fixing typo in path /dev/null

### PR DESCRIPTION
**Pull request by SudoBrendan**
### Which issue this PR addresses:

N/A - informal

### What this PR does / why we need it:

There is a typo in the paths, which results in a `no such file or directory` error that will always exit `1` and make these  two  IF statements always fail.

### Test plan for issue:

I discovered this bug after following the [deploy an int-like env](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md#deploying-an-int-like-development-rp). This PR is a partial fix to getting that to work.

### Is there any documentation that needs to be updated for this PR?

I'm unsure, but I doubt it.

### CODE REVIEW

**Review by bennerv — APPROVED** [review]
LGTM - good catch.  Waiting for green CI/E2E then merging.

**Review by petrkotas — APPROVED** [review]
Oh man, thanks for catching this typo. LGTM and really good eye!

**Review by s-amann — APPROVED** [review]

**Pull request merged**
