### PR TITLE
Multi version refactor

### PR DESCRIPTION
**Pull request by ross-bryan**
### Which issue this PR addresses:

Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15585074/

### What this PR does / why we need it:
Refactors the `ListVersions` to a proxy resource, but in doing so found the entire `ListVersions` resource struct repetitive, and instead reused the `OpenShiftVersion` that was defined in the internal and external API to all use that in the external API definition.

### Test plan for issue:
unit tests, by fire

### Is there any documentation that needs to be updated for this PR?
should probably communicate and discuss with David and Amber

### CODE REVIEW

**Review by darthhexx — CHANGES_REQUESTED** [review]
Thank you for working on this and overall it looks lgtm.

A few changes required for multi-version to work, clean up the `get-versions` output, and skip validating empty `ClusterProfile.Version`'s during installation (otherwise not specifying a version causes cluster creation to fail).

None of the files that needed fixing were changed in this PR, so here's a diff for review:
```diff
diff --git a/pkg/api/v20220904/openshiftcluster_validatestatic.go b/pkg/api/v20220904/openshiftcluster_validatestatic.go
index 80ccd968f..e2757b89c 100644
--- a/pkg/api/v20220904/openshiftcluster_validatestatic.go
+++ b/pkg/api/v20220904/openshiftcluster_validatestatic.go
@@ -151,7 +151,10 @@ func (sv openShiftClusterStaticValidator) validateClusterProfile(path string, cp
                return api.NewCloudError(http.StatusBadRequest, api.CloudErrorCodeInvalidParameter, path+".domain", "The provided domain '%s' is invalid.", cp.Domain)
        }
 
-       if isCreate && !validate.RxInstallVersion.MatchString(cp.Version) {
+       // there is Version empty when the create cluster request has not specified the install version and
+       // frontend.validateInstallVersion sets it to version.InstallStream.Version, so ignore empty cp.Version's
+       // TODO: call frontend.validateInstallVersion before the static validation or incorporate it into the validation
+       if isCreate && cp.Version != "" && !validate.RxInstallVersion.MatchString(cp.Version) {
                return api.NewCloudError(http.StatusBadRequest, api.CloudErrorCodeInvalidParameter, path+".version", "The provided version '%s' is invalid.", cp.Version)
        }
 
diff --git a/python/az/aro/azext_aro/custom.py b/python/az/aro/azext_aro/custom.py
index fc7b814dd..5c5ff3241 100644
--- a/python/az/aro/azext_aro/custom.py
+++ b/python/az/aro/azext_aro/custom.py
@@ -106,6 +106,7 @@ def aro_create(cmd,  # pylint: disable=too-many-locals
             resource_group_id=(f"/subscriptions/{subscription_id}"
                                f"/resourceGroups/{cluster_resource_group or 'aro-' + random_id}"),
             fips_validated_modules='Enabled' if fips_validated_modules else 'Disabled',
+            version=install_version or '',
         ),
         service_principal_profile=openshiftcluster.ServicePrincipalProfile(
             client_id=client_id,
@@ -142,7 +143,6 @@ def aro_create(cmd,  # pylint: disable=too-many-locals
                 visibility=ingress_visibility or 'Public',
             )
         ],
-        install_version=install_version or '',
     )
 
     sp_obj_ids = [client_sp_id, rp_client_sp_id]
@@ -224,7 +224,11 @@ def aro_list_admin_credentials(cmd, client, resource_group_name, resource_name,
 
 
 def aro_get_versions(client, location):
-    return client.install_versions.list(location)
+    openshift_verions = client.open_shift_versions.list(location)
+    versions = []
+    for ver in openshift_verions.additional_properties["value"]:
+        versions.append(ver["properties"]["version"])
+    return sorted(versions)
```

**Review by bennerv — APPROVED** [review]
lgtm

**Review by bennerv — APPROVED** [review]

**Pull request merged**
