### PR TITLE
CI VM Fixes

### PR DESCRIPTION
**Pull request by bennerv**
### Which issue this PR addresses:

ADO-12389136

### What this PR does / why we need 
This PR addresses a couple bugs: 

We're now using rhel8 CI VMs to build our RP & code.  As a result we are using `podman`.  Sometimes `podman` will terminate or Azure DevOps will terminate VSTS agents running when a job is cancelled, and podman won't finish it's commands but the process will be killed.  `podman` keeps track of this process in: `/tmp/run-1000/libpod/tmp/pause.pid`, where `1000` is the uid of the user running the `podman` command.  This will always be `cloud-user/1000` as that's what we have it set to when we create the CI VMs.

After some time, the `/tmp` filesystem fills up.  Due to golang relying on the `/tmp` filesystem for builds, the golang unit tests and builds fail.  A cronjob was added to find files not accessed within an amount of time in the `/tmp` filesystem and delete them.  

### Test plan for issue:

Create new CI VMs
* ensure that the cronjob is present in the root crontab
* ensure that the new CI VMs & bumping the VSTS agent version doesn't break any pipelines
* profit

### Is there any documentation that needs to be updated for this PR?

Nope.

### CODE REVIEW

**Comment by bennerv** [comment]
Need to test the extension script used to spin up the CI VMs before merging.  /hold for now.

**Comment by bennerv** [comment]
These VMs are already deployed and tested.  Should resolve some CI failures as well.  Should be good to merge if the code looks good, else we can change it and redeploy them.

**Review by karanmagdani — APPROVED** [review]
LGTM!

**Review by jewzaam — APPROVED** [review]

**Review by bryanro92 — APPROVED** [review]
lgtm pls fix

**Pull request merged**
