### PR TITLE
Update azure-cli coordinates in mirror

### PR DESCRIPTION
**Pull request by tsatam**
### Which issue this PR addresses:

No Jira

### What this PR does / why we need it:

Updates our image reference for the Azure CLI to a known working version

### Test plan for issue:

- mirroring pipeline works

### Is there any documentation that needs to be updated for this PR?

No

### How do you know this will function as expected in production? 

N/A (image only used ad-hoc)

### CODE REVIEW

**Review by tiguelu — APPROVED** [review]
LGTM.

Small, nit. Is there any other doc that references this image that we need to update apart from https://dev.azure.com/msazure/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/553880/MDM-MDSD-and-Fluentbit-image-refresh  ?

Not related to the new image being mirrored, although it references the digest which stopped working.

**Comment by tiguelu** [comment]
> LGTM.
> 
> Small, nit. Is there any other doc that references this image that we need to update apart from https://dev.azure.com/msazure/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/553880/MDM-MDSD-and-Fluentbit-image-refresh ?

Disregard that comment, this was a different image unrelated to the image being mirrored.

**Comment by tsatam** [comment]
> Small, nit. Is there any other doc that references this image that we need to update apart from https://dev.azure.com/msazure/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/553880/MDM-MDSD-and-Fluentbit-image-refresh ?

Good point, we have various ad-hoc SOPs that instruct us to utilize the Azure CLI image, some of them provide specific coordinates while others do not. 

We should replace any explicit occurrences of `azure-cli:2` with `azure-cli:cbl-mariner2.0` in documentation.

**Comment by tiguelu** [comment]
> > Small, nit. Is there any other doc that references this image that we need to update apart from https://dev.azure.com/msazure/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/553880/MDM-MDSD-and-Fluentbit-image-refresh ?
> 
> Good point, we have various ad-hoc SOPs that instruct us to utilize the Azure CLI image, some of them provide specific coordinates while others do not.
> 
> We should replace any explicit occurrences of `azure-cli:2` with `azure-cli:cbl-mariner2.0` in documentation.

I changed a direct reference to the image in upstream repo in one SOP, and found another 4 referencing the ACR image. I will raise a task to update them after a successful mirroring happens.

**Pull request merged**
