### PR TITLE
Deprecate RAW image

### PR DESCRIPTION
**Pull request by mjudeikis**
### Which issue this PR addresses:

Fixes lack of RAW image in new regions

### What this PR does / why we need it:

RAW image is being deprecated

### Test plan for issue:

In canary 

### Is there any documentation that needs to be updated for this PR?

no

### CODE REVIEW

**Comment by mjudeikis** [comment]
Filesystem state after testing:
```
[root@rp-9248ef5d-000000 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  118M  3.8G   3% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda2        32G  5.0G   27G  16% /
/dev/sda1       497M  128M  369M  26% /boot
/dev/sdb1        16G  2.1G   13G  14% /mnt/resource
overlay          32G  5.0G   27G  16% /var/lib/docker/overlay2/2c40d0a177680335072396d068bd2f24b471cd3c43a662639438da066b886ab2/merged
overlay          32G  5.0G   27G  16% /var/lib/docker/overlay2/7a9e4d8cf7e9e1826132bb9b863e5708434901e3566655ea84467d7003697b83/merged
overlay          32G  5.0G   27G  16% /var/lib/docker/overlay2/e333300e3f4ec3497f94956758149b958a5d97ebbb9dd57424476a8fdcde190b/merged
shm              64M     0   64M   0% /var/lib/docker/containers/f99b9a71e9ff5e402319a97581a54f147b423aec3537334e3178c6736fb5c661/shm
shm              64M     0   64M   0% /var/lib/docker/containers/daee00dd442e9373744def9d3a34824b98a8e69b8451745832f4de37e3f0515f/shm
shm              64M     0   64M   0% /var/lib/docker/containers/37534f66a7d8a52f450c7a8f4dce6e236356090447b68973455a446c34afb54f/shm
tmpfs           799M     0  799M   0% /run/user/0
tmpfs           799M     0  799M   0% /run/user/1000
```

**Review by jim-minter — APPROVED** [review]

**Pull request merged**
