### PR TITLE
change SP for prod

### PR DESCRIPTION
**Pull request by mjudeikis**
### Which issue this PR addresses:

Fixes SP ref for Production public cloud

### What this PR does / why we need it:

I suspect App id is wrong in public cloud.

### Test plan for issue:

by :fire: 

### Is there any documentation that needs to be updated for this PR?

No

### CODE REVIEW

**Review by m1kola — APPROVED** [review]
In this case I assume that you know what you are doing.

**Comment by mjudeikis** [comment]
> In this case I assume that you know what you are doing, becuase there is nothing to review in this PR.

I don't :D bit of guessing here is involved :D

**Comment by nilsanderselde** [comment]
e2e failure was flake: "Resource quota of cores exceeded"

**Pull request merged**
