### PR TITLE
Remove podman network causing outbound latency

### PR DESCRIPTION
**Pull request by bennerv**
### Which issue this PR addresses:
Fixes a latency issue with outbound connections caused by the creation of dedicated podman networks.  

### What this PR does / why we need it:
Fix a regression in outbound connection latency.  

### Test plan for issue:
RP deploy

### CODE REVIEW

**Comment by bennerv** [comment]
untested as it requires a full-dev env.

**Comment by jaitaiwan** [comment]
PR no longer needed. Closing out.

**Comment by bennerv** [comment]
e2e isn't testable by these scripts.  Running CI but everything was good.  Again these script changes are untested.

**Review by SrinivasAtmakuri — APPROVED** [review]
LGTM!

**Review by tsatam — APPROVED** [review]

**Pull request merged**
