### PR TITLE
adds s-amann to codeowners

### PR DESCRIPTION
**Pull request by s-amann**

### CODE REVIEW

**Review by facchettos — APPROVED** [review]
:rocket: :tada:

**Review by bennerv — APPROVED** [review]
Heck yes! :rocket:  :rocket:  :rocket:  :rocket:  :rocket:  :rocket:

**Review by m1kola — APPROVED** [review]

**Comment by ross-bryan** [comment]
are we sure?

**Comment by ross-bryan** [comment]
congrats @s-amann 🎉

**Pull request merged**
