### PR TITLE
[ARO-7345] smoke test automation for aro-operator log 

### PR DESCRIPTION
**Pull request by bitoku**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-7345

### What this PR does / why we need it:

This PR adds smoke test that confirms there is no error log in aro-operator logs.
This is labelled as "smoke", so it doesn't run automatically in CI.

### Test plan for issue:

Run `E2E_LABEL=smoke make test-e2e` locally.

### Is there any documentation that needs to be updated for this PR?

N/A

### How do you know this will function as expected in production? 

This is a part of tests.

### CODE REVIEW

**Review by kimorris27 — COMMENTED** [review]
The change and the motivation make sense, but I'm not sure if I really think the operator is this stable... let's see if E2E passes the new test 😅

**Comment by mociarain** [comment]
> let's see if E2E passes the new test 😅

So E2E won't run the smoke tests as is: https://github.com/azure/ARO-RP/blob/09a56b1c466c54d10fb9132e18ff3dd78ce0533b/Makefile#L6


Having said that I agree with your concerns @kimorris27. If there's some error in the aro-operator logs do we care? I think the answer is "it depends" but given the scope of where we use the smoke tests I'm happy to ship this as is. Thoughts?

**Review by mociarain — APPROVED** [review]

**Comment by kimorris27** [comment]
>So E2E won't run the smoke tests as is: https://github.com/azure/ARO-RP/blob/09a56b1c466c54d10fb9132e18ff3dd78ce0533b/Makefile#L6
>
>Having said that I agree with your concerns @kimorris27. If there's some error in the aro-operator logs do we care? I think the answer is "it depends" but given the scope of where we use the smoke tests I'm happy to ship this as is. Thoughts?

Oh, that's right; I forgot. That makes sense to me. We can tweak the test later on if this causes too many "flakes" in the smoke tests.

**Review by kimorris27 — APPROVED** [review]

**Pull request merged**
