### PR TITLE
Fix runtime error

### PR DESCRIPTION
**Pull request by mjudeikis**

### CODE REVIEW

**Comment by troy0820** [comment]
@mjudeikis Wasn't this the same bug @thekad found in closed PR #734?  I thought Angus wanted this in?

**Comment by mjudeikis** [comment]
@troy0820 yes, but too early. Will raise again :) too much multitasking happening :D

**Comment by thekad** [comment]
This got fixed by @jim-minter in #825 (or at least partially)

**Comment by mjudeikis** [comment]
actions do not have `f` there is panic somewhere hidden in here... I got it once, but didn't tracked "/

**Pull request closed without merging**
