### PR TITLE
don't monitor spot node conditions

### PR DESCRIPTION
**Pull request by nilsanderselde**
### Which issue this PR addresses:

Fixes [10557489](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10557489)

### What this PR does / why we need it:

[SPOT VMs](https://docs.microsoft.com/en-us/azure/virtual-machines/spot-vms) can go offline at any time, so SRE should not be concerned if they become deallocated.

### Test plan for issue:

Manual testing

### Is there any documentation that needs to be updated for this PR?

No

### CODE REVIEW

**Comment by mjudeikis** [comment]
@nilsanderselde how does MCO reacts to this? Who cleans the machines? Nodes? If nobody does we should not be raising this as a bugzilla/feature too before we add this hack to stop as from monitoring nodes.
And overall im not sure how much Im comfortable doing this. Basically cluster with autoscalled and only Spot instances would be nit monitored at all. Or legit issues on stop instances will be ignored. 

I think this wrong approach.

**Comment by nilsanderselde** [comment]
@mjudeikis 
>legit issues on stop instances will be ignored
Yeah, that's a concern.

>how does MCO reacts to this
It's supported. I've seen it work from the OpenShift console. Looks like it's handled pretty gracefully.

Here are the docs for OCP:
https://docs.openshift.com/container-platform/4.6/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-non-guaranteed-instance_creating-machineset-azure

My concern was that Geneva Monitoring will see the drop-off in metrics for those deallocated nodes. Maybe there is a better way we could fine tune our alerting. I suppose we could just see if it really causes a problem if people start using this already-supported feature.

@jewzaam WDYT?

**Comment by mjudeikis** [comment]
> @mjudeikis
> 
> > legit issues on stop instances will be ignored
> > Yeah, that's a concern.
> 
> > how does MCO reacts to this
> > It's supported. I've seen it work from the OpenShift console. Looks like it's handled pretty gracefully.
> 
> Here are the docs for OCP:
> https://docs.openshift.com/container-platform/4.6/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-non-guaranteed-instance_creating-machineset-azure

Doc does not tell me if nodes are left or whats happens with machine objects... It might be we dont have problem here at all it object is gone - monitors will just stop monitoring.

**Comment by nilsanderselde** [comment]
> Doc does not tell me if nodes are left or whats happens with machine objects... It might be we dont have problem here at all it object is gone - monitors will just stop monitoring.

The node goes away when the Spot VM is deallocated. I thought that the sudden absence of metrics would trigger recurring NodeReady incidents for the same clusters, but if that's not the case, then this isn't necessary. I was pretty sure I've seen NodeReady incidents for no-longer-existent nodes.

**Comment by mjudeikis** [comment]
Lets not try to solve problem we don't know we will have.
Feel free to replace on of the nodes on shared cluster with StopInstance and time will show

**Comment by nilsanderselde** [comment]
> Lets not try to solve problem we don't know we will have.
> Feel free to replace on of the nodes on shared cluster with StopInstance and time will show

OK, I'd already added a spot machineset, so I'll leave it scaled to 1 and we can see what happens.

**Comment by nilsanderselde** [comment]
It's become clear that there are a lot of NodeReady incidents which stem from spot VMs. Cx will have docs on how to kick the nodes, and they will know what they are getting into. We shouldn't be concerned with this noise.

**Pull request merged**
