### PR TITLE
Remove portal v1

### PR DESCRIPTION
**Pull request by hawkowl**
### Which issue this PR addresses:

Followup to https://github.com/Azure/ARO-RP/pull/3445 , and clears up some v1 POAMS

### What this PR does / why we need it:

Removes the V1 portal

### Test plan for issue:

CI, E2E, local testing

### Is there any documentation that needs to be updated for this PR?

N/A

### How do you know this will function as expected in production? 

E2E exists for the v2 portal, plus local testing of the auth flow

### CODE REVIEW

**Review by tsatam — APPROVED** [review]
LGTM

We could probably benefit from removing the `v2` name/folder and just maintaining a single portal, but that can be a follow-up effort

**Review by mociarain — APPROVED** [review]
Lovely

**Review by SudoBrendan — CHANGES_REQUESTED** [review]
Lovely, thanks for the follow up while I was on PTO to get this across the line :)

Can you please pull in the changes to [gdnsuppress](https://github.com/Azure/ARO-RP/pull/3445/files#diff-a7fdb3f611082ade077d9a6aef98db36c848387741e8a41a26ffa800a5993421) and [gitignore](https://github.com/Azure/ARO-RP/pull/3445/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) as well?

**Comment by hawkowl** [comment]
@SudoBrendan done, I'll find an INT candidate

**Review by tiguelu — DISMISSED** [review]
LGTM, pending INT tests.

**Comment by hawkowl** [comment]
We can't test in INT right now, but I tested locally and verified that the auth/login flow functions as expected.

**Review by cadenmarchese — APPROVED** [review]

**Review by mociarain — APPROVED** [review]

**Pull request merged**
