### PR TITLE
document on usage of how to make adminaction API calls to localrp

### PR DESCRIPTION
**Pull request by SrinivasAtmakuri**
### Which issue this PR addresses:

Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12838475/

### What this PR does / why we need it:

Documents the procedure on how to make AdminAction API call(s)
to a localrp running a Dev Cluster to perform below actions.,

1. List Clusters
2. List Azure Resources
3. PUCM
4. Cluster Upgrade
5. Get Cluster Details
6. View Serial Console logs of a VM

### CODE REVIEW

**Review by petrkotas — APPROVED** [review]
@SrinivasAtmakuri have checked the commands and their functionality? 
As far as I can tell they should.

Besides thanks for this. LGTM

**Review by bryanro92 — CHANGES_REQUESTED** [review]
LGTM, one nit to squash commits.
Thanks!

**Comment by SrinivasAtmakuri** [comment]
@petrkotas Yes, I have tested the commands and their functionality.

**Review by hawkowl — APPROVED** [review]

**Pull request merged**
