### PR TITLE
Fix make aro build in onebranch

### PR DESCRIPTION
**Pull request by hawkowl**
### Which issue this PR addresses:

Fixes an oversight in #3719 

### What this PR does / why we need it:
Makes the build work again, hopefully

### Test plan for issue:

Build pipeline fixes, so the build pipeline should be able to test for it

### Is there any documentation that needs to be updated for this PR?

N/A

### How do you know this will function as expected in production? 
N/A

### CODE REVIEW

**Review by ArrisLee — DISMISSED** [review]

**Review by yjst2012 — APPROVED** [review]
LGTM

**Review by SudoBrendan — APPROVED** [review]
LGTM

**Comment by SudoBrendan** [comment]
azp run ci,e2e

**Review by jaitaiwan — APPROVED** [review]

**Review by tiguelu — APPROVED** [review]
Thank you Amber

**Pull request merged**
