### PR TITLE
set MDSD_MSGPACK_SORT_COLUMNS to perf column sorting on MDSD side

### PR DESCRIPTION
**Pull request by gvanderpotte**
### Which issue this PR addresses:

Try to avoid hitting max schema count issue on RP logs search by setting MDSD_MSGPACK_SORT_COLUMNS=1 in mdsd env variables

### What this PR does / why we need it:

Try to avoid hitting max schema count issue on RP logs search by setting MDSD_MSGPACK_SORT_COLUMNS=1 in mdsd env variables. 

### Test plan for issue:

- Are there unit tests? No
- Are there integration/e2e tests? No
- If it is not possible to write automated tests, explain why and document how
  to manually test and verify the feature. Will need to test in INT

### Is there any documentation that needs to be updated for this PR?

N/A

### CODE REVIEW

**Review by bennerv — APPROVED** [review]
LGTM - do you know if we're seeing this issue in INT too?  We could test the changes there temporarily until they end up in prod to see if we see an improvement.

**Review by s-amann — APPROVED** [review]
lgtm, can't wait to see if this helps!

**Review by ross-bryan — DISMISSED** [review]

**Review by jhoreman — APPROVED** [review]
Change looks good. Do we have documentation on how to reproduce/test in INT?

**Comment by gvanderpotte** [comment]
Will test in INT first - stay tuned

**Review by bennerv — DISMISSED** [review]
Looks good after deploying to INT.  Rebase and we should be able to merge this in https://jarvis-west.dc.ad.msft.net/563BEFC3

**Review by ross-bryan — APPROVED** [review]

**Pull request merged**
