### PR TITLE
Refactor /test/util/applens package names/directories

### PR DESCRIPTION
**Pull request by SudoBrendan**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-4264 (partial)

### What this PR does / why we need it:

This is an initial refactor to make subsequent changes that allow tests to mock HTTP client calls via mocking httpTransport. This refactor changes the name of this package to reflect its directory name, and also allows us to extend the changes to have a `test/util/http/client` library alongside it.

### Test plan for issue:

Current build and tests should pass to prove this rename works. This is only a refactor of current test related code.

### Is there any documentation that needs to be updated for this PR?

N/A

### CODE REVIEW

**Review by s-amann — APPROVED** [review]
lgtm

**Review by AldoFusterTurpin — APPROVED** [review]
LGTM. Thanks

**Comment by bennerv** [comment]
e2e failure unrelated to change made.  Merging

**Pull request merged**
