### PR TITLE
Move Fluentbit RPM Package to Container in Gateway

### PR DESCRIPTION
**Pull request by bennerv**
### Which issue this PR addresses:

Fixes [ADO14306029](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14306029)

### What this PR does / why we need it:

Consistency between the RP and gateway fluentbit image usage. 

Should match #1635  very closely.  

### Test plan for issue:

Deploy to INT and ensure gateway logging still works

### Is there any documentation that needs to be updated for this PR?

Nope

### CODE REVIEW

**Review by petrkotas — APPROVED** [review]
LGTM, thanks

**Comment by bennerv** [comment]
Holding on testing in INT to confirm it still works.

**Review by ross-bryan — APPROVED** [review]
lgtm

**Comment by bennerv** [comment]
Deployed to INT, this looks good; I am still seeing logs for gateway.  

https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=54899741&view=logs&j=3c7d1bfc-207c-57c7-bfba-8d4b44a0467d&t=1acb40ae-22aa-5025-303e-cfb82f77661f 

https://jarvis-west.dc.ad.msft.net/8EFB22F2 -> shows logs for gateway for commit: 4e12b5d

**Pull request merged**
