### PR TITLE
Replace usage of mgmt/network use by azuresdk/armnetwork

### PR DESCRIPTION
**Pull request by bdematte**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-12543

### What this PR does / why we need it:

Removing calls to mgmt/network in favor to azuresdk/armnetwork

### Test plan for issue:

This is being called during cluster install so covered by E2E. 

### Is there any documentation that needs to be updated for this PR?

No need for documentation update specific to this sub task as technical migration. 

### How do you know this will function as expected in production? 

Technical migration, standard monitoring will be use to monitor it works as expected.

### CODE REVIEW

**Review by bitoku — APPROVED** [review]

**Review by tiguelu — CHANGES_REQUESTED** [review]
@bdematte The origin branch is in your fork, but it needs to be a branch in the ARO-RP repo itself in order for CI pipelines to work. Can you please push your branch from your fork into ARO-RP repo and update the pull request?

**Comment by bitoku** [comment]
Duplicate of https://github.com/Azure/ARO-RP/pull/3993

**Pull request closed without merging**
