### PR TITLE
refactor test/util/log to allow matching of arbitrary log fields

### PR DESCRIPTION
**Pull request by jim-minter**
refactor test/util/log to allow matching of arbitrary log fields - I'd like to be able to do this for the new portal work

### CODE REVIEW

**Comment by jim-minter** [comment]
@hawkowl can I get a +1 please?

**Review by mjudeikis — APPROVED** [review]

**Comment by jim-minter** [comment]
Changes are entirely to unit tests, ignoring e2e fail (have requested more quota) and merging

**Pull request merged**
