### PR TITLE
Fix: Broken pull path

### PR DESCRIPTION
**Pull request by petrkotas**
The original path is not working as it is blocked for writing,
Using the pipeline default instead

Signed-off-by: Petr Kotas <pkotas@redhat.com>

### CODE REVIEW

**Review by gvanderpotte — COMMENTED** [review]
approved

**Review by gvanderpotte — APPROVED** [review]
Approved

**Comment by petrkotas** [comment]
I am merging to fix the broken config pull to speed up the current release. The change is localized into the very small part of the pipelines and does not affect the RP code base.

**Comment by petrkotas** [comment]
I have merged the PR in order to unblock the ongoing release.

**Pull request merged**
