### PR TITLE
Bump install timeouts

### PR DESCRIPTION
**Pull request by mjudeikis**
### Which issue this PR addresses:

We have seen a number of InternalServer error because Vm's not being able to report in time.
I was thinking If it worth a separate feature flag for this or not?

### What this PR does / why we need it:

Increate timeout for bootstrap node (master being ready)
Increate timeout for console ready (scheduled on nodes)

### Test plan for issue:

na

### Is there any documentation that needs to be updated for this PR?

na

### CODE REVIEW

**Comment by jim-minter** [comment]
@mjudeikis are you absolutely sure that the installs in question would have succeeded were it not for the timeout?

**Comment by mjudeikis** [comment]
> @mjudeikis are you absolutely sure that the installs in question would have succeeded were it not for the timeout?

No I'm not. But debugging these issues is hard. And customers usually complain about intermittent issues. So maybe we can have feature flag for Timeouts so we can test this in prod and get feedback before applying?

**Review by jim-minter — CHANGES_REQUESTED** [review]
I don't want to merge a change like this without being very sure of its value, because it will make failure conditions slower to appear for everyone else.  I was not able to conclude from the support case associated with this PR that making this change would actually have helped.

**Comment by mjudeikis** [comment]
> I don't want to merge a change like this without being very sure of its value, because it will make failure conditions slower to appear for everyone else. I was not able to conclude from the support case associated with this PR that making this change would actually have helped.

The problem is that same as with other issues we had - its hard to conclude this would help.
So I was thinking maybe add this behind feature flag? So if a customer comes with a similar issue, we can ask them to enable it and test. This way we would be able to control it when we need it

**Comment by jim-minter** [comment]
Fundamentally, if it's going to succeed, the cluster will create even if the RP times out.  As long as the user doesn't delete the failed cluster we should be able to look at it via Geneva Logs / Actions / admin portal to determine what's going on and why.

**Comment by mjudeikis** [comment]
> Fundamentally, if it's going to succeed, the cluster will create even if the RP times out. As long as the user doesn't delete the failed cluster we should be able to look at it via Geneva Logs / Actions / admin portal to determine what's going on and why.

We know we have an issue with resource lag to a provision in some regions during peeks or just bad timing. And those times we gett these abstract incidents as customers saw the failure. They do no go and check if it succeeded as we already told them it didn't.  How we can address issues like this ?

**Pull request closed without merging**
