### PR TITLE
SRE portal UI: allow searching in the dropdown element

### PR DESCRIPTION
**Pull request by m1kola**
### Which issue this PR addresses:

Fixes work item [№9234092](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9234092/)

### What this PR does / why we need it:

Allows copy-paste or partial search in the drop-down elemet with cluster resource IDs.

### Test plan for issue:

Screenshot 2021-02-03 at 16 58 46

### Is there any documentation that needs to be updated for this PR?

No, it is just an UI change

### CODE REVIEW

**Review by nilsanderselde — COMMENTED** [review]
awesome!

**Comment by jim-minter** [comment]
looks great - check the bindata.go ?

**Comment by jim-minter** [comment]
I think .DS_Store might be the problem

**Review by mjudeikis — APPROVED** [review]

**Pull request merged**
