### PR TITLE
Update go version to 1.18

### PR DESCRIPTION
**Pull request by petrkotas**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-2127 

### What this PR does / why we need it:
Update go to 1.18
Signed-off-by: Petr Kotas <pkotas@redhat.com>

### CODE REVIEW

**Review by mbarnes — CHANGES_REQUESTED** [review]
There's a few mentions of Go 1.17 under `docs`, can you update those too please?

- `prepare-a-shared-rp-development-environment.md`
- `prepare-your-dev-environment.md`
- `updating-dependencies.md`

Also, what about Go toolset base images?  There's a reference in `Dockerfile.aro-multistage` and a couple under `.pipelines/onebranch`.

**Comment by cadenmarchese** [comment]
@mbarnes @petrkotas heads up that if we bump the `LinuxContainerImage` go-toolset images in the OneBranch templates, we'll need to [push that version up to our Isolated ACR](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/189194/CDPx-Container-Images?anchor=isolated-acr)

**Comment by petrkotas** [comment]
I believe that I do not have to update devCIVMs, which are to be deprecated with the move to the 1ES.
I also found that in https://github.com/Azure/ARO-RP/blob/master/cmd/aro/mirror.go#L161 go1.18.4 is already mirrored. Is this enough @cadenmarchese ?

**Review by cadenmarchese — COMMENTED** [review]
@petrkotas https://github.com/Azure/ARO-RP/blob/master/cmd/aro/mirror.go#L161 mirrors to our prod ACRs. The isolated ACR (`cdpxb8e9ef87cd634085ab141c637806568c00.azurecr.io`) is a different ACR used to host base images for use in OneBranch pipelines specifically. We use this mirrored image in the following places:

- https://github.com/Azure/ARO-RP/blob/master/.pipelines/onebranch/pipeline.buildrp.official.yml#L16-L17
- https://github.com/Azure/ARO-RP/blob/master/.pipelines/onebranch/pipeline.buildrp.pullrequest.yml#L16-L17

If we update to 1.18 everywhere, we will probably want to update this image as well.

**Comment by mbarnes** [comment]
Out of scope for this pull request, but we should document in one place (ADO?) all the steps needed to fully bump the ARO RP and related resources to a newer Go version.  It's a nontrivial process and what documentation there is appears to be scattered, afaict.

**Review by cadenmarchese — APPROVED** [review]
The build + push with the new go-toolset image is working well: https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=68493225&view=results and other CI changes here appear to be working as well.

**Review by mbarnes — APPROVED** [review]

**Review by hawkowl — APPROVED** [review]
THE GO OF TOMORROW!!!! (well, close enough)

**Review by darthhexx — APPROVED** [review]

**Pull request merged**
