### PR TITLE
Add hack script to install multiple clusters at one time.

### PR DESCRIPTION
**Pull request by bitoku**
### Which issue this PR addresses:

Fixes N/A
As a part of https://issues.redhat.com/browse/ARO-6198

### What this PR does / why we need it:

Once we have the install in prod regions, we need to install some clusters to make sure that there is no increase in installer failure rate.
This hack script can help to test multiple installations at one time in a region. 

### Test plan for issue:

Ran in local.

### Is there any documentation that needs to be updated for this PR?

yes I updated the doc.

### How do you know this will function as expected in production? 

You can check the output of the script to see the result.

### CODE REVIEW

**Review by mociarain — COMMENTED** [review]
LGTM but I wonder why this stuff isn't in the installer repo?

**Comment by bitoku** [comment]
Good question. To be honest, I didn't think of that.

If I had to say, the installer repo has scripts that are needed when developing the installer, but the process like [ARO-6198](https://issues.redhat.com/browse/ARO-6198) is conducted after we deployed a new release in each region (I mean not when we are developing it).

But I don't have the preference. I want to know what others think.

**Comment by tiguelu** [comment]
> @mociarain Good question. To be honest, I didn't think of that.
> 
> If I had to say, the installer repo has scripts that are needed when developing the installer, but the process like [ARO-6198](https://issues.redhat.com/browse/ARO-6198) is conducted after we deployed a new release in each region. Also ARO-RP is more accessible because everyone clones it.
> 
> But I don't have the preference. I want to know what others think.

I didn't think of it either, but it makes more sense to have the script in the wrapper repo. Probably even the .md file with the instructions too. If we move the content from upstream-difference.md too, we probably should keep the old file just with a link to the new one (since it is linked from other docs, jiras and wikis).

**Comment by bitoku** [comment]
Thank you all!
I will close this PR and will make new ones to here and the installer repo to migrate the `upstream-difference.md`.

**Pull request closed without merging**
