### PR TITLE
Bumping the MDSD MDM Fluentbit images in RP

### PR DESCRIPTION
**Pull request by Shivkumar13**
### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-3894

### What this PR does / why we need it:

Bump the Fluentbit, MDM, and MDSD images we use so that they don't get flagged as P0/P1/P2 vulnerabilities that need to be resolved.

### Test plan for issue:

MDSD still ingests logs in INT
Fluentbit still ingests logs in INT
MDM still shows metrics coming in INT

### Is there any documentation that needs to be updated for this PR?

No

### CODE REVIEW

**Comment by bennerv** [comment]
@shivkumar13 e2e won't pass until you run the mirroring PR pipeline that mirrors the mdsd images into INT.  Just an FYI.

**Review by jhoreman — COMMENTED** [review]
Change looks good but need to mirror the images so e2e can pass :)

**Comment by petrkotas** [comment]
`https://github.com/Azure/ARO-RP/pull/3106` @Shivkumar13 would you please run make generate and update the PR, we can than proceed with it

**Comment by Shivkumar13** [comment]
@petrkotas Done! 

Ran the pipeline to push the Fluentbit to INT, need to wait for that to be over so that we can run the e2e on this PR again.

**Pull request merged**
