### PR TITLE
bump azidentity package

### PR DESCRIPTION
**Pull request by weinong**
### Which issue this PR addresses:

this PR bumps the azidentity package to break down https://github.com/Azure/ARO-RP/pull/1970 and to pave way for https://issues.redhat.com/browse/ARO-2527

### What this PR does / why we need it:

- bump azidentity package
- make corresponding changes in applensclient

### Test plan for issue:
existing UTs

### Is there any documentation that needs to be updated for this PR?
N/A

### CODE REVIEW

**Comment by weinong** [comment]
tagging @mbarnes @bennerv @SudoBrendan

**Review by mbarnes — DISMISSED** [review]
Since we're already using azidentity in a limited capacity, I'm good with bumping the version here and then rebasing https://github.com/Azure/ARO-RP/pull/2667 on it.

**Review by niontive — DISMISSED** [review]

**Review by s-amann — DISMISSED** [review]

**Review by cblecker — DISMISSED** [review]

**Review by s-amann — DISMISSED** [review]

**Review by cblecker — APPROVED** [review]

**Comment by cblecker** [comment]
e2e is still failing, but it looks like an e2e problem itself. I'm going to merge this anyways as this seems fine when I test locally and we need to rebase some other PRs once this is in.

**Pull request merged**
