### PR TITLE
Revert "Merge pull request #1483 from swiencki/retryDelete"

### PR DESCRIPTION
**Pull request by mjudeikis**
This reverts commit 278e59131d68dfc1068937d58099f36bc99db248, reversing
changes made to 060007680842a5e80ba56d7a67c1054fda717b83.

### CODE REVIEW

**Comment by jewzaam** [comment]
@mjudeikis curious why we're removing the retry.  We can expect future issues on delete.  We could log and alert/report on it somewhere.  But having a retry helps reduce flakes on delete.

**Comment by mjudeikis** [comment]
@jewzaam because it can obfuscate other issues we want to know about. In general retries just for retries without understanding why we are retrying is bad practice (even worse followed by sleep). Lets say we have "other issue" and this masks it. We never notice it in canary region and it gets rolled out to all production regions. So we would be running with hidden bug all the time and not even know about it. Until somebody removed/changes something and everything goes :banana: and have those moments where "Why I changed this and it fails on the other side of the code where I didn't even touched". We all been in those situations where something somewhere obfuscates behavior we didn't accounted for :) 

I prefer to understand before retry and not do blind retries on each failure.

In general in this codebase we retry only when:
1. retry is understood and we can't do anything (AAD propagation, retry in ARM where ARM consistency is poor)
2. when we have temporary fix like this. But we tend to remove them later.

**Comment by jewzaam** [comment]
@mjudeikis we need to find the right balance. We _know_ delete can fail.  This retry isn't to work around a specific failure but to address all those intermittent issues we find.  We have some options though.  

If we keep the retry (in current or improved form, not what I want to focus on here) we can report on retries.  This gets us information on the failure but ultimately the delete didn't fail as a retry was successful.  We can put in place some process to generate a report for review.  Until the investigations that resulted in the retry we literally ignored the delete failures.  BUT someone had to review the pipeline to see why it failed.  If it is a blocking failure the retry will fail and ultimately still fail the pipeline.  Now we must investigate to move forward with an RP release.  

My goal is to reduce the flakes and manual review of failures for RP releases.  Given we ignore the delete failures today we have no idea if they are material.  With a retry, if we see a delete failure it immediately is know to be important.  I want to see similar changes on create as we treat them the same and create has even more flakes.

So, how do we reduce the amount of failures for E2E that are a material impact to RP releases without missing a real issue for deletion?

**Comment by mjudeikis** [comment]
| We know delete can fail.

Deletes should not fail without a reason unknown to us. 

| This retry isn't to work around a specific failure but to address all those intermittent issues we find.

We will never be able to find issue is they are masked/hidden. To add retry is easy. To write code which does not need retries - not so much. 

| My goal is to reduce the flakes and manual review of failures for RP releases. Given we ignore the delete failures today we have no idea if they are material. With a retry, if we see a delete failure it immediately is know to be important. I want to see similar changes on create as we treat them the same and create has even more flakes.

Lets be honest, nobody ever said "I will go and check how my retry I added 2 month ago Is behaving and does it needs to looking back". If we leave this we will leave it forever. Hence we dont add code which hides the errors. We would be ignoring them if we leave this retry. With retry it will never report failure to CI. And I would be VERY against create code retry too.

**Comment by m1kola** [comment]
> We _know_ delete can fail.

Everything can fail, but it doesn't mean that we should _blindly_ wrap everything in a retry loop.

> If we keep the retry (in current or improved form, not what I want to focus on here) we can report on retries. This gets us information on the failure but ultimately the delete didn't fail as a retry was successful. We can put in place some process to generate a report for review.

I'm up for gathering the data and establishing a cycle of reviewing and acting on the data. But until we have data and the process in place for this I'm not in favour of masking failures behind retries. Without retries the chances of finding a legit issue in CI before it hits production are higher.

> My goal is to reduce the flakes and manual review of failures for RP releases. Given we ignore the delete failures today we have no idea if they are material.

We don't completely ignore delete failures: we investigate them when we seem them in CI. This helped us to find PLS issue.

We also used to occasionally review past creation/deletion failures to see if we can make any improvements. Thanks to reviewing past failures _and_ failures in CI we found issues with AAD sync delay which actually needed retries to make the creation  process more reliable. We made a number of improvements like better logging for SREs and more customers-friendly errors for things which we can not control. We also changed our deletion process: we now remove the most expensive resources early to avoid charging the customers for unusable clusters. These are just few things I can remember.

I'm not saying it is perfect solution, but it is better than just hiding failures.

> I want to see similar changes on create as we treat them the same and create has even more flakes.

I would like us to look into failures and reduce the chances of failures instead of just retrying and hoping for the best. It is very easy to add a retry, but very hard to remove one from a codebase full of retries: you don't know whether it is still actually needed. It is going to be a schrodinger's retry: you don't know the impact of removing it without actually removing it and running this code in prod for a while.

I think retries should serve a specific purpose. I'm ok to retry in places with of eventual consistency. Where we know we can see an AAD sync delay or where we know that update might fail due to concurrent processes making their own updates (e.g. almost any Kube API update).

But adding blind retries without reporting and acting on them is a bad idea in my opinion. We should strive to improve stability by either improving our deletion/creation process ourselves in the ARO RP codebase or reporting issues to relevant teams. Hiding issues behind retry is going to be very close to ignoring the them.

So from here I see the following possible options:

* Wrap everything with retries, accept this technical debt and the fact that it is going to be very hard to get rid of it. And hope for the best.
* Try to improve creation/deletion process. This in turn has sub options:
    * Act reactively. We are currently doing this: we review CI failures + sometimes do ad-hoc reviews of prod failures.
    * Act proactively: add metrics (if current ones are not enough) and target specific part of the process. If something needs a retry for a good reason - so be it. If we can improve in some other way - awesome. This is going to be slow, I imagine.

**Pull request merged**
