### PR TITLE
clientId validation

### PR DESCRIPTION
**Pull request by jim-minter**
xref #200

### CODE REVIEW

**Comment by mjudeikis** [comment]
tbh I dont understand fully background of this PR even after reading the issue

**Comment by jim-minter** [comment]
> tbh I dont understand fully background of this PR even after reading the issue

Fair comment.  There are several issues here:

1- because `err` was shadowed in `(done bool, err error)`, if token.EnsureFresh() never succeeded, we didn't return an error and then ParseUnverified failed because token.OAuthToken() was not valid.  Should have been caught in a unit test.

2- the 30s wait timeout is longer than the time ARM will wait for us to respond, so the end user got a 504 gateway timeout in the above case.

3- we would retry on any token.EnsureFresh() failure.  In fact we should only try in the case that we think there's a stale cache problem.  If the client ID is found and the credentials are clearly wrong, we should not keep retrying.

Leaving #200 open because this still needs unit tests.

**Comment by mjudeikis** [comment]
It is not the first time shadowed return trips us. Worth considering stop using them in our code base? Improves readability and fewer errors like this?

**Comment by jim-minter** [comment]
the 1st problem here is lack of unit testing.

**Comment by jim-minter** [comment]
the 1st problem here is lack of unit testing.

**Comment by mjudeikis** [comment]
It is not the first time shadowed return trips us. Worth considering stop using them in our code base? Improves readability and fewer errors like this?

**Pull request merged**
