### PR TITLE
9433950: Document Pipelines

### PR DESCRIPTION
**Pull request by coreyperkins**
This is a "living" document of the pipeline(s) implementation. Additionally it serves as a single source of documentation for Ev2 concepts that are being used within.

### CODE REVIEW

**Comment by mjudeikis** [comment]
@coreyperkins  what is your plan for this document? Do you want to work with this as a PR or want to merge and iterate?

**Comment by mjudeikis** [comment]
@coreyperkins squash please

**Comment by mjudeikis** [comment]
@coreyperkins @jewzaam what we want to do with this one?

**Comment by jewzaam** [comment]
@mjudeikis  I'm good with this being part of the RP.  Expectation will be it is updated as pipelines are updated.  If it makes sense to move to a wiki that could be done too but I'll go ahead and +1 to get it in and started.

**Comment by jewzaam** [comment]
Oh wow, this is an old PR.  @coreyperkins  @mikeandescavage  is this up to date (he says knowing the answer: no), is this what we want to use for documenting things?

**Comment by coreyperkins** [comment]
Closing. The decision was made to do this in the ADO Wiki with only a pointer to that Wiki in the ARO-RP docs. I will do that in a fresh PR.

**Pull request closed without merging**
