### PR TITLE
Enable SBOM on all OneBranch pipelines

### PR DESCRIPTION
**Pull request by mikeandescavage**
### Which issue this PR addresses:

Fixes: https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/12997379/
Related: https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/12932704

### What this PR does / why we need it:

This is a requirement driven by Microsoft

### Test plan for issue:

N/A

### Is there any documentation that needs to be updated for this PR?

N/A

### CODE REVIEW

**Review by bennerv — APPROVED** [review]
LGTM - waiting on green CI to merge

**Review by bryanro92 — APPROVED** [review]
lgtm,
@mikeandescavage - do you know if these sboms are shipped anywhere or just stay in the pipelines?

**Comment by mikeandescavage** [comment]
@bryanro92 - the SBOM manifests generated are included in the published artifacts of the build.  Based on their documentation, it does not appear that it gets shipped anywhere else.

**Pull request merged**
