### PR TITLE
Minor change in deploy-dev-rp.md

### PR DESCRIPTION
**Pull request by SrinivasAtmakuri**
### Which issue this PR addresses:

It is better to explicitly call out CLUSTER=<cluster-name>, as in the azure portal we see dev clusters created with
name `cluster`.

### CODE REVIEW

**Review by ross-bryan — APPROVED** [review]
hey @SrinivasAtmakuri, lgtm. could you please add a description beyond one word `fixes` to the pull request? Thanks

**Review by jhoreman — APPROVED** [review]
LGTM but please include a more in depth description of the change and the reason for it :)

**Review by petrkotas — APPROVED** [review]

**Comment by petrkotas** [comment]
@SrinivasAtmakuri We can merge it after the description is updated

**Comment by SrinivasAtmakuri** [comment]
@petrkotas I have updated the PR description, Thank you!

**Review by darthhexx — APPROVED** [review]

**Pull request merged**
