### PR TITLE
fluentbit pipeline

### PR DESCRIPTION
**Pull request by mjudeikis**
### Which issue this PR addresses:

Fluentbit image is stale. We need way to build it in prod and int fast. This should do

### What this PR does / why we need it:

Automate the build

### Test plan for issue:

Test in pipelines

### Is there any documentation that needs to be updated for this PR?

No

### CODE REVIEW

**Comment by gvanderpotte** [comment]
LGTM

**Comment by Makdaam** [comment]
Closed my PR. This will need an update of the wiki https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/165661/fluentbit-Image-Management

/lgtm

**Review by hawkowl — APPROVED** [review]

**Pull request merged**
